### PR TITLE
Release 7: Fix wrong PHP type when creating instance of `xoctUser`

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR suggest a fix for #265 .

### CODE REVIEW

**Review by marcusm7 — COMMENTED** [review]
A (very short) test of the PR shows: The PR fixes the issue https://github.com/opencast-ilias/OpenCast/issues/269. Creation of new series objects works again.

**Comment by dagraf** [comment]
Thank you very much for testing. Since tests were successful and @Amstutz: Can you please review this PR and comment or merge it depending on your findings? Thx!

**Comment by rfcmaXi** [comment]
I have just downloaded the pull and can also confirm that you can now create new (or old) series again.

**Comment by ckozianka** [comment]
I can confirm that, too. Without this PR, I wasn't able to upgrade from 5.2 and 5.6 to the new release_7.

**Comment by Amstutz** [comment]
thx merged for 7, however for 8 we should rather set a fixed type for the param and check the usages of the function. @dagraf can you discuss this in the upcoming meeting and let me know on how we should proceed here. ftm, I will NOT push this to 8 (7 only).

**Comment by Amstutz** [comment]
In a short chat with @chfsx we decided to pick this nevertheless to 8, to keep the version close. still, the function should be refactored further.

**Pull request merged**
