### PR TITLE
[Release 8] Paella Player - adding custom getVideoId function to enable restoreLastTime config option

### LINKED ISSUE #289: Memorization of last position in video is not per video
**Describe the bug**
When leaving the Paella Player in the middle of a video, the last position is remembered. Unfortunately this position is not remembered per video, i.e. when playing **another** video afterwards it starts from the remembered position of the last one.

**To Reproduce**
1. Go to 'Play' for a video
2. The player with the thumbnail is visible. Now click the Play button.
3. Play some time, pause the video, remember the time stamp the video has stopped.
4. Leave video and open another one for playing.
5. The player with the thumbnail is visible. Now click the Play button.
6. The new video starts from the time position the previous one has been left.

**Expected behavior**
A new video should play right from the start resp. the position I left exactly this video the last time.

**Environment (please complete the following information):**
 - ILIAS version:  7.30
 - PHP version: PHP 7.4
 - Plugin version: 7.0.3 (May 2024)
 - Opencast version: 14.6.
 - Browser: Firefox, Chromium

**Note**
Until there is a solution a certain flag in the _config.json_ of the player should be set to false. Unfortunately I do not know which one, please someone else add this info!

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #289,

### New additionals
- a new function `getVideoIdFunction` is added to the paella player js,
- during Paella Player initialisation, we now use this function as for `getVideoId` param.
- the `restoreLastTime` config is enabled again!

### Upgrades:
- `paella-basic-plugins` is upgraded to `v1.44.10`
- `paella-core` is upgraded to `v1.49.7`
- `paella-slide-plugins` is upgraded to `v1.48.1`

That would make sense to test Paella Player features through, because we upgrade the paella player packages!

### CODE REVIEW

**Comment by snoesberger** [comment]
Thanks for fixing this! In our test environment (with this PR) the play position is now correctly memorzied for each event.

**Comment by dagraf** [comment]
Since tests were successfull:

@chfsx : Can you please review this PR and merge it if everything is fine or comment it, if not? Thx!

**Review by chfsx — APPROVED** [review]
Thanks a lot, I will merge this to the next release

**Comment by dagraf** [comment]
@chfsx Ist dieser PR auch im 9er-Release des Plugins drin?

**Comment by marcusm7** [comment]
@dagraf ich hab nur die stichprobe auf 

```
    "restoreLastTime": {
      "enabled": true,
```

in Plugin 9.0.3 gemacht. Diese Change ist mit drin und der Player merkt sich die Playback-Position je Video (getestet mit Firefox, Ilias 9.7).

**Comment by chfsx** [comment]
Yes this has been picked to v9.0.1: https://github.com/opencast-ilias/OpenCast/blob/release_9/CHANGELOG.md#version-901

**Pull request merged**
