### PR TITLE
[Release 8] Upgrade paella-user-tracking to v1.42.5

### LINKED ISSUE #323: Event title information is not sent to Matomo Media Analytics plugin
**Describe the bug**
In order for the Matomo Media Analytics plugin to work correctly, the paella player user tracking plugin needs to send a video title information. Without this information, all statistics within the Matomo Media Analytics plugin will be combined under a video with the title "unknown".
At the moment there is no information about the title being sent from the OpenCast plugin to Matomo at all.
According to [this documentation](https://developer.matomo.org/guides/media-analytics/options) the title information is extracted from one of these sources:

>   Media Analytics will detect the media title by searching for the following pieces of information:
>
>   - firstly, the data-matomo-title HTML attribute.
>   - next, the data-piwik-title HTML attribute.
>   - Media title from YouTube / Vimeo player.
>   - title HTML attribute.
>   - finally, the alt HTML attribute.

**To Reproduce**
1. Matomo with Media Analytics active
2. ILIAS Opencast Plugin Paella Player configured to send data to Matomo
3. Play different videos
4. All statistics in Matomo summarized under "unknown"

**Expected behavior**
Would it be possible to add the Opencast event-ID with the mentioned HTML attribute to the paella player within the Opencast Plugin? (I'd prefer to use the event ID instead of the event title to be sure to have a unique identifier.)

**Environment (please complete the following information):**
 - ILIAS version: 8
 - Plugin version: 8
 - Opencast version 15

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #323

It only contains the build changes after upgrading `paella-user-tracking` plugin  to v1.42.5

### CODE REVIEW

**Comment by ferishili** [comment]
@snoesberger, please give it a try and write your feedback here.

Another question: is this change only for `release_8`?

**Comment by snoesberger** [comment]
I have successfully tested this PR.

Unfortunately the Opencast event ID is not available within the Paella player at the moment, only the video title (`metadata.title`) can be referenced in the paella player config. @ferishili as discussed in the Matrix chat, it would be really nice if the Opencast event ID could be made available.

**Comment by ferishili** [comment]
`videoid` as well as `seriesid` is now available in metadata:

`il.Opencast.Paella.player.data.metadata.videoid`
`il.Opencast.Paella.player.data.metadata.seriesid`

**Comment by snoesberger** [comment]
Many thanks for the quick implementation!
We were now able to successfully configure and test the paella player to sent video and series ID to Matomo. This is part of the config we used for our tests:

```
...
"es.upv.paella.matomo.userTrackingDataPlugin": {
            "enabled": true,
            "context": [
                "userTracking"
            ],
            "server": "https://matomo-test.org/",
            "siteId": "1",
            "trackerUrl": {
                "php": "matomo.php",
                "js": "matomo.js"
            },
            "matomoGlobalLoaded": false,
            "cookieType": "tracking",
            "mediaAnalyticsTitle": "${metadata.videoid}",
            "logUserId": true,
            "events": {
                "category": "ILIAS PaellaPlayer",
                "action": "${event}",
                "name": "${eventData}"
            },
            "customDimensions": {
                "1": "${metadata.videoid}",
                "2": "${metadata.seriesid}",
                "3": "${metadata.title}"
            }
        },
...
```

The statistic data is successfully sent to Matomo both for live streams and VoD.

**Comment by dagraf** [comment]
Since tests were successfull and @ferishili: Can you please prepare this PR for merging and then hand it over to @chfsx for a review and the actual merge? Thx!

**Comment by ferishili** [comment]
@chfsx the PR is ready to merge, no rebase is needed atm!

**Comment by chfsx** [comment]
Thanks a lot, merged to v8.1.4!

**Pull request merged**
