### PR TITLE
[Enhancement] Dynamic Title for Straigthtopublishing workflow parameter in Thumbnail upload

### LINKED ISSUE #367: Thumbnail upload: Shown name of "Straigthtopublishing" workflow parameter in "Note" should not be hard coded
**Describe the bug**
When I have activated the thumbnail file upload in the plugin config and then want to upload a thumbnail, there is the following note shown in the upload window:

«NOTE: "Straight to publishing" Processing setting must be enabled for this feature to work.»

The expression "Straight to publishing" is hard coded. But we have configured this workflow to call "Automatisch publizieren (Auto publish)" (see screenshots) and users end up asking themselves what this "Straight to publishing setting is. 

**To Reproduce**
1. Have thumbnail upload activated in your plugin config
2. Open a Opencast series and click on 'Upload'
3. Scroll down to see the note stated above

**Expected behavior**
The expression shown in the note should show the title which is configured for the "straightToPublishing" parameter under "Workflow parameters". If this parameter is not configured then show "Straight to publishing".

**Screenshots**

Shown note when uploading a video:
Bildschirmfoto 2024-11-14 um 10 54 47

Configured workflow parameter:
Bildschirmfoto 2024-11-14 um 10 55 23

**Environment (please complete the following information):**
 - ILIAS version: 8.14
 - Plugin version: 8.1.4
 - Opencast version 15
 - Browser: Firefox

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #367
For more info please refer to the issue.

### CODE REVIEW

**Comment by dagraf** [comment]
It works as expected, but the messages should be improved slightly.

DE: «ACHTUNG: Die Verarbeitungseinstellung "TITLE OF WF-PARAMETER" muss aktiviert sein, damit das Vorschaubild korrekt angezeigt wird.»
EN: «NOTE: The processing setting "TITLE OF WF-PARAMETER" must be activated for the preview image to be displayed correctly.»

**Comment by ferishili** [comment]
Hi @dagraf,
Text adjustments are there, please give it a try.

**Comment by dagraf** [comment]
Looks good, thx!

@chfsx : Can you please review this PR and merge it if everything is fine or comment it, if not? Thx!

**Comment by chfsx** [comment]
Thanks a lot, all fine! I rebased and merged this locally, since we have to take those fixes to the ILIAS 9 version as well, I squashed the commits for easier picking in https://github.com/opencast-ilias/OpenCast/commit/5b9a93a152787bf40c522dcdfa4ea53836383bde

Released new Version [v8.2.7](https://github.com/opencast-ilias/OpenCast/commit/fbc927e8188aeff6732582563e8ebb4bbe785733)

**Pull request closed without merging**
