### PR TITLE
Fix/7/194 /  New Caching Service

### PR DESCRIPTION
**Pull request by chfsx**
This PR introduces a new, better caching service that works in the same way as the caching service in ILIAS 9. This means that we will be able to switch to the new service very easily with an ILIAS 9 version of the Opencast plugin.

The PR fixes issue #194.

However, there is currently one change in behavior to mention: Until now there was the setting "ILIAS Caching Service", which used a cache or not depending on the settings in ILIAS. 
I had to change this setting to an explicit "APCu" caching. However, if Memcached, for example, is also required, please let me know and I could then implement this.

I was able to implement the "Database" caching mechanism more comprehensibly and reliably with the new implementation.

### CODE REVIEW

**Comment by Hufschmidt** [comment]
Commits seems to be working with ILIAS 7.26. 

While we normally use Memcache ourselves I'd say this is mostly historical for us when the distributed nature of Memcache had an advantage over APCu (which is per Worker-Cache). Of course If you want to take the time to implement the Memcache backend as well I'm happy to test.

---

One side-note: I tried using `srsolutionsag:fix/7/194` branch directly (not cherry-picking/merging) and got the following whoopsie when trying to update the plugin language:

```
ilErrorHandling::{closure}:50 1 Class srag\DIC\OpenCast\Database\DatabaseDetector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ilDBInterface::primaryExistsByFields) in /srv/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/vendor/srag/dic/src/Database/DatabaseDetector.php:19#0 /srv/www/ilias/libs/composer/vendor/filp/whoops/src/Whoops/Run.php(514): Whoops\Run->handleError()
#1 [internal function]: Whoops\Run->handleShutdown()
#2 {main}  
```

But I guess its because https://github.com/opencast-ilias/OpenCast/issues/187 is missing from that branch...

**Comment by Hufschmidt** [comment]
Verified caching with `apcu_cache_info()`, seems to be working with APCu enabled.

**Small addendum:**
You can enable the _APCu Cache_ option without having the PHP APCu module installed/active. Maybe a check for APCu availability should be added. Although enabling the _APCu Cache_ option without any APCu module enabled did also not throw any PHP errors strangely enough...

**Comment by chfsx** [comment]
Hi @Hufschmidt thanks a lot for your testing!

> Of course If you want to take the time to implement the Memcache backend as well I'm happy to test.

I would suggest that we rebuild the memcache implementation at a later time if this is desired, because it requires a more extensive configuration (memcached nodes).

> But I guess its because https://github.com/opencast-ilias/OpenCast/issues/187 is missing from that branch?

yes, that will be the problem, this should no longer occur in the merged version and if it does, we would have to record it in a new issue.

> Verified caching with apcu_cache_info(), seems to be working with APCu enabled.

thanks for the test!

> You can enable the APCu Cache option without having the PHP APCu module installed/active.

good point! i'll add that in a moment

**Comment by dagraf** [comment]
@Hufschmidt: Have you already had time to test the latest commits of @chfsx to this PR?

**Comment by Hufschmidt** [comment]
Oh no, did not explicitly test yet, but can do so tomorrow. :+1:

**Comment by chfsx** [comment]
I will update the PR to resolve conflicts and increase plugin version

**Comment by chfsx** [comment]
PR updated

**Comment by Hufschmidt** [comment]
Tested as working in current version of plugin.

**Pull request merged**
