### PR TITLE
Dynamic Workflows

### LINKED ISSUE #13: Definable workflow parameters
**Use Case**

It should be possible to set workflow parameters not only to _true_. It should be possible to specify further workflow parameters as checkboxes.

**Desired implementation**

In addition to Boolean parameters, checkboxes, strings and numbers should be possible as workflow variables.

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #13 

### Description
see description in issue.

### Solution
Now configuration panel is loaded, converted into ILIAS style and presented to users directly from Opencast, so you will have dynamic parameters to interact with and then those values will be sent back to opencast.

the whole concept/approach is that:

#### Admins:
- Plugin setting tab "Workflows" now contains 2 sub-tabs! (Settings & Workflow definitions list)
- Admin must set the workflow tags to extract from the list of workflow definitions from Opencast.
- Admins are able view/edit/delete those extracted workflows in the definitions list sub-tab
- Admins are able to define translations string for each workflow definition option in the Start Workflow list selection by providing `workflow_selection_text_{workflow definition identifier} ` e.g. `workflow_selection_text_{republish-metadata}#:#Veröffentlicht` in the lang strings.
- Admins are able to reset or update the list of workflow definitions by two provided button in the in the definitions list sub-tab.

#### Users:
- When the list is set by admin, users will have "Start Workflow" button in the event Action menu.
- The modal with a dropdown to select configured workflows will be displayed and users are able to select one.
- Description of that wf will be displayed now (if any)
- Configuration Panel of selected WF will be displayed (if any)
- Users are able to interact with configuration panel and enter values etc.

## NOTE:
This PR increase the plugin version to 5.3.2 and a db update No. 43, so it might have conflicts with current PRs!

### CODE REVIEW

**Comment by ferishili** [comment]
Thanks a lot @dagraf. I am going apply the changes ASAP

**Comment by ferishili** [comment]
Hi @dagraf,
new changes are pushed, please have a look. Thanks.

**Comment by dagraf** [comment]
Thanks for the changes, which look good. Only the "Configuration Panel" is not yet renamed. But for the moment I suggest we leave it as it is and change the wording at a later stage.

Therefore and @Amstutz: Can you please review this PR and comment it if needed or merge it. Thx!

**Comment by ferishili** [comment]
PS: The Configuration Panel is renamed, you only need to refresh the languages again 😄

**Comment by dagraf** [comment]
Renaming of Configuration Panel: I did refresh the languages but maybe some cache settings is playing a trick on me. I will retest later and comment here if needed.

**Comment by reiferschris** [comment]
> Hi @dagraf, new changes are pushed, please have a look. Thanks.

I also tested the changes to the configuration panel with our workflows, they look fine. Thanks for coming up with the improvement @dagraf and @ferishili

**Review by reiferschris — APPROVED** [review]

**Comment by chfsx** [comment]
PR in https://github.com/elan-ev/ilias-opencast-plugin/pull/4 to resolve conflicts

**Pull request merged**
