### PR TITLE
[Release 8] Chat Improvements

### LINKED ISSUE #83: Live-Chat: Introduce live-scrolling and hints to show that there are hidden messages
**Problem**
In the Chat of a Live-Stream: If there are more messages than fit in my screen, all new messages are hidden. To be able to see them I have to actively scroll down. Like this it can especially for teachers following the live-chat in the lecture hall but also for students watching at home easily happen that they miss the latest questions or messages.

**Solution**
Implement a auto scrolling features and a message for showing new but hidden messages.

1. Auto scrolling: As long as a user has not scrolled at all or as soon as he reaches the bottom of the chat via scrolling, new messages automatically get shown at the very bottom of the chat. Which means that the chat automatically jumps/scrolls to the latest message.
2. Message indicating new but hidden messages: When a users actual view of the chat does not show the very bottom of it because he did scroll upwards in the chat, new messages get indicated with a message (red button with white writing): "XY new message(s)" (DE: "XY neue Nachricht(en)") > see screenshot. This button is clickable. By clicking on it, the chat autmatically scrolls to the very bottom which shows the newest messages and which leads to the auto scrolling feature taking over (because the view of the viewers includes the very bottom of the chat. 

Bildschirmfoto 2022-11-09 um 13 03 23

### LINKED ISSUE #84: Live-Chat: Make it more prominent so it's not possible to oversee it
**Problem**
When the chat of a live-stream is still empty it can easily been overseen that there is a chat available, because there is no title an no clear separation between the player and the chat.

**Solution**
Add a title "Chat" to the chat 'column' and add a line which separates the player from the chat (see screenshot).

MicrosoftTeams-image (7)

### PR DESCRIPTION
**Pull request by ferishili**
This PR,
fixes #84,
fixes #83  

### Improvments
- Devider between chat container and video
- Chat title
- Scroll only the messages container
- Lots of css improvements
- Fix width to 290 pixel in desktop view; to recognize the mobile and desktop view (important)
- Auto scrolling to the end of the list:
   - On mobile -> to the top
   - On desktop -> to the end
- New Message info box (+ red dot) when the scroll is not at the end of the list!
- Inteligent seen/unseen mechanism when the message item is in view!
   - Removeing the red dot
   - Decreasing the number of new messages
- JS code improvements

### CODE REVIEW

**Comment by samuelinniger** [comment]
We (Unibe) just tested the PR on our ILIAS-Test Installation (ILIAS v8.13). Somehow, most of the new features are missing (?), e.g. the chat title. I can only see the new separators. 
Is something missing in the PR, or do we need to adjust something on our installation?

Tested on Firefox and Safari. See attached video.
https://github.com/user-attachments/assets/0daed19e-2316-47c3-aac5-c75a6e61179c

@okaufman FYI

**Comment by ferishili** [comment]
> Is something missing in the PR, or do we need to adjust something on our installation?

Hi @samuelinniger
this PR is intended to add the list of improvements in [description](https://github.com/opencast-ilias/OpenCast/pull/310#issue-2377912770).

Therefore, I would assume that your browser cache should be cleared first, then the chat server node should be restarted in order to pick up the changes!

**Comment by dagraf** [comment]
I did some testing. Here my results:
- Auto-scrolling and "New Message info box" work as expected. Thx!
- The title is also present now. But I would suggest to make the following optimizations (see mockup):
  - Make box of the title a bit 'narrower' (i mean less high).
  - Center the text "Chat" not only horizontally but also vertically.
  - Use a darker grey for the text "Chat".
- The devider between chat container and video is missing in my live-stream. I did clear my browser cache and also when opening an "Private Window" (in Firefox) the devider is not there (see screenshot).

**Missing divider:**
Bildschirmfoto 2024-08-05 um 17 43 56

**Mockup:**
Bildschirmfoto 2024-08-05 um 17 53 50

**Comment by dagraf** [comment]
I found one additional small problem: When opening or freshly loading a browser tab with a running livestream the spinning wheel seems to be broken (see screenshot).

Bildschirmfoto 2024-08-05 um 18 00 17

**Comment by ferishili** [comment]
Hi @dagraf,
Thanks for the feedback. I would like to bring your attention to the following points, and the other changes I will apply right away:

> * The devider between chat container and video is missing in my live-stream. I did clear my browser cache and also when opening an "Private Window" (in Firefox) the devider is not there (see screenshot).

The divider is there and has been implemented.

https://github.com/opencast-ilias/OpenCast/blob/4cf8b866d7d3e697a51870eca074b54b21351d7b/src/Chat/node/public/css/chat.css#L14

Screenshot 2024-08-06 at 08 51 34

The **solution**, in your case, is to have this PR in both sides (the plugin side and the node side).

> I found one additional small problem: When opening or freshly loading a browser tab with a running livestream the spinning wheel seems to be broken (see screenshot).

Also for the refresh icon, it is there, but it could not be loaded properly in your dual-server setup, due to CSP restrictions!

https://github.com/opencast-ilias/OpenCast/blob/4cf8b866d7d3e697a51870eca074b54b21351d7b/src/Chat/node/templates/index.ejs#L172

Screenshot 2024-08-06 at 09 08 00

**Comment by ferishili** [comment]
@dagraf, the changes for the title color & height as well as border colors are applied.
Please check them out.
Thanks in advance.

Screenshot 2024-08-06 at 10 03 11

**Comment by dagraf** [comment]
I tested the changes and can aprove it. Everything looks fine now and works as expected. Thx!

Therefore and @ferishili, can you please prepare this PR for merging and pass it over to @chfsx for a review? Thx!

**Comment by chfsx** [comment]
Thanks a lot, merged locally to v8.1.4!

**Pull request closed without merging**
