### PR TITLE
[FIX] issue with checkboxes  in workflow config form

### PR DESCRIPTION
**Pull request by chfsx**
This PR fixes the issue described in #343. Please note that thi has only testes with the "duplicate-event" workflow mentioned in the issue ticket. I'm not sure if we can use checkboxes handling in general like this (read comments in #343 how opencast handles this checkboxes).

### CODE REVIEW

**Comment by dagraf** [comment]
When testing this PR, I was able to duplicate an event having the checkbox "Do not use copy suffix" activated. Also the copy did not contain any suffix. Which is fine.

But when I try to duplicate an event having the same checkbox DEactivated (not checked) the following error message appears:

Bildschirmfoto 2024-11-14 um 11 31 36

@chfsx Can you please have a look at it? Thx!

**Comment by chfsx** [comment]
Thanks for the feedback! I updated the PR to avoid this issue, this was PHP version dependant and I was testing with 7.4.

**Comment by dagraf** [comment]
Thanks for the fix. I newly tested this PR and now both checkboxes work as expected.

@ferishili: Can you please review this PR and comment it if needed or merge it, if everything is fine? Thx!

**Review by ferishili — APPROVED** [review]
Thanks for changes, it looks good to me.
That would be great if @reiferschris could also test this PR, more in the area of download sub-publications, since there are some code changes there!

**Comment by reiferschris** [comment]
@ferishili sorry I currently don't have the time to test this PR, mainly because I don't have a working ilias deployment where I could check out a PR.

**Comment by dagraf** [comment]
Thx for the hint @ferishili to test publication sub-ussages. 

In doing so i found one issue: Deleting an existing sub-usage is not possible. When I click on "Actions" and the "Delete" the following error message appears (see screenshot).

@chfsx : Can you please have a look at it? Thx!

Bildschirmfoto 2024-11-28 um 10 27 51

**Comment by chfsx** [comment]
Thanks for the feedback, the issue wasn't directly related to the other fix, but i managed to fix that as well. and there was another issue while deleting publication usages (not sub-), which is now fixed as well

**Comment by dagraf** [comment]
I successfully retested the fix for https://github.com/opencast-ilias/OpenCast/pull/366#issuecomment-2505644751.

Therefore and @chfsx: Can you please merge this PR? Thx!

**Comment by chfsx** [comment]
This PR has been merged locally and is part of https://github.com/opencast-ilias/OpenCast/releases/tag/v8.3.0

**Pull request closed without merging**
