### PR TITLE
Paella 6.5.6

### PR DESCRIPTION
**Pull request by mliradelc**
Updates Ilias plugin paella to version 6.5.6

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @mliradelc 

Thx a lot for the changes and taking care of the paella version? I am somewhat new to this, so one question:

- [ ] Issues: Will this resolve any known issues? Are there changes in the new version, that could lead to new issues?

Thx

**Comment by ebbertd** [comment]
I just tried out this branch on our ILIAS 6 test system. When I try to play a video, all I get is a white page.

**Comment by ebbertd** [comment]
I just tried this branch again and it seems to work now.

**Comment by Amstutz** [comment]
Thx for Testing!

**Pull request merged**
