### PR TITLE
[Release 8] Avoid starting workflow when event is in ingesting or pending state

### LINKED ISSUE #148: Events in the status "Ingesting" should not have the user action "Start Workflow"
_**Describe the bug**_
After a scheduled event terminates on a hardware capture agent (in our case the Extron SMP), the video gets uploaded to the Opencast Server. During the upload, the status is/changes to "Ingesting"/"importiert".

In ILIAS, this "ingesting" event is still marked/shown as scheduled event during this upload. 
**Bug**: the user is able to start a workflow for "ingesting" events. The action "start workflow" --> "Publish" ist available.
This will result in a failed event in Opencast. Fortunately, the upload will be processed in a (new) event in Opencast. 

_**To Reproduce**_
1. Schedule a meeting in Opencast
2. After the recording, wait for the status to change to "Ingesting"
3. --> In ILIAS, start the Action "Start Workflow" --> "Publish"

_**Expected behavior**_
The action "Start worfklow" should be deactivated for events with the status "Ingesting"/"Importiert".
It probably would be best to handle the event same as a "running" event: other thumbnail, other text message, no user actions at all.

_**Screenshots**_
Status in Opencast: 
Bildschirm­foto 2023-03-06 um 17 21 05

In ILIAS, users are able to start a workflow  for the ingesting event.

_**Environment (please complete the following information):**_
ILIAS version: 7.18
Plugin version: 5.1.0
Opencast version 12.0
Browser: Firefox

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #148 

### Solution
- Introducing Running processing state, including INGESTING and PENDING event status.
- Add this checker when rendering the start workflow button

NOTE: Due to the lack of possibility for me to reproduce the scheduling and live streaming, please help me test these scenarios.

Please also provide any further improvement, such as infos, texts etc. so that I can apply in this PR

### CODE REVIEW

**Comment by snoesberger** [comment]
Thanks @ferishili, this fix works for us, I was no longer able to start a publishing workflow during the ingest phase of a recording.

During the ingest phase of an event, the plugin displays the text "Geplante Aufzeichnung / Scheduled Event":
grafik

Instead, a text like "Ingesting and Preprocessing Event" would be nice.

**Comment by dagraf** [comment]
> Instead, a text like "Ingesting and Preprocessing Event" would be nice.

I would rather see something like this there:
- EN: "Preprocessing ongoing, not visible to students"
- DE: "Aufzeichnung wird verarbeitet, für Studierende nicht sichtbar"

**Comment by ferishili** [comment]
Text adjustments are applied, please check them out.
Thanks

**Comment by dagraf** [comment]
Thx for the adjustments.

@ferishili: Can you please prepare this PR for merging and when done contact @chfsx? Thx!

**Pull request merged**
