### PR TITLE
Proposal/captainhook and codestyle

### PR DESCRIPTION
**Pull request by chfsx**
As discussed today, I'd like to introduce php-cs-fixer and captain-hook to ensure PSR12 for development.
In this branch you can install githook with 

```bash
./vendor/bin/captainhook install -c captainhook.json -f
```
after installing this, the `pre-commit` hook will check staged files für the PSR12-config in doc/CodeStyle/php-cs-fixer-config.php

You can fix the code using 
```bash
./vendor/bin/php-cs-fixer fix --config doc/CodeStyle/php-cs-fixer-config.php PATH_TO_CODE
```

Sorry, since we have all dependencies in vendor pushed in the repo, this PR seems huge...

### CODE REVIEW

**Comment by chfsx** [comment]
This PR doesn't change the whole code to PSR-12, I will open a new PR with changed codestyle after merging this

**Comment by ebbertd** [comment]
I just installed the githook as stated above and tried to see if it works. When trying to commit something I get:
```
$ git commit -m "Testcommit"                     
pre-commit: 
 - ./vendor/bin/php-cs-fixer fix --config doc/CodeStyle/php-cs-fi... : failed

failed to execute: ./vendor/bin/php-cs-fixer fix --config doc/CodeStyle/php-cs-fixer-config.php --dry-run --using-cache=no  classes/class.ilOpenCastConfigGUI.php


In ConfigurationResolver.php line 537:
                                                                    
  Cannot read config file "doc/CodeStyle/php-cs-fixer-config.php".  
                                                                    

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]
```

**Comment by Amstutz** [comment]
Hi @okaufman and @Amstutz both failed to run:
`./vendor/bin/captainhook install -c captainhook.json -f`

We both get: 
`PHP Parse error:  syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /Users/amstutz/Programming/ILIAS Install/ilias/Customizing/global/plugins/Repository/RepositoryObject/OpenCast/vendor/symfony/console/Application.php on line 231`

For 7.4 and similar error for PHP8. 

@chfsx : In general we approve the PR. Feel free to merge as soon as we resolved the above issues.

**Comment by ebbertd** [comment]
I still get the same error and am starting to think it might be my settings here.

**Comment by okaufman** [comment]
This works now for me using php7.4.
Thank you very much

**Pull request merged**
