### PR TITLE
Fix/7/remove dictrait & Opencast PHP Library integration

### LINKED ISSUE #187: ErrorException thrown with message "Class srag\DIC\OpenCast\Database\DatabaseDetector
Hi @mjansenDatabay
in which version of the plugin did this error occur for you? Also which version or better commit of ilias itself did you use?

sorry, maybe I was wrong. A colleague of mine sent me the following error ...

```bash
root@octa04-vm01:/srv/www/my.ilias.de/admin/ilias_errors# cat 83f24_1477.log
Whoops\Exception\ErrorException thrown with message "Class srag\DIC\OpenCast\Database\DatabaseDetector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ilDBInterface::primaryExistsByFields)"

Stacktrace:
#2 Whoops\Exception\ErrorException in /srv/www/my.ilias.de/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/vendor/srag/dic/src/Database/DatabaseDetector.php:19
#1 Whoops\Run:handleError in /srv/www/my.ilias.de/ilias/libs/composer/vendor/filp/whoops/src/Whoops/Run.php:514
#0 Whoops\Run:handleShutdown in [internal]:0


-- GET Data --

ref_id                   : 31
admin_mode               : settings
ctype                    : Services
cname                    : Repository
slot_id                  : robj
pname                    : OpenCast
cmd                      : refreshLanguages
cmdClass                 : ilobjcomponentsettingsgui
cmdNode                  : 1d:m0
baseClass                : ilAdministrationGUI
```

... and pointed me to THIS issue here. Bug maybe this is a different problem. If yes, please ignore my comment.

_Originally posted by @mjansenDatabay in https://github.com/opencast-ilias/OpenCast/issues/169#issuecomment-1688644855_

### PR DESCRIPTION
**Pull request by ferishili**
This PR contains 2 major parts including PR #184 and Opencast PHP Library integration. Therefore it closes #184 in favor of following upcoming related changes here.
It is a development-collaboration between @chfsx  and @ferishili! 

### Testing
As it is considered as a major refactoring/integration change and affects almost everything, this PR needs a in-depth testing! (please refer to Suggestion beforehand)

### Suggestion
It is recommended to apply PR #180, before this PR, in order to make it work seamlessly also in fresh installations!

### Resolution
This PR fixes #187, due to the fact that DICTrait is now removed

### CODE REVIEW

**Comment by dagraf** [comment]
@chfsx: We just startet testing this PR and till now everyhting works fine. Where should I report bugs I might find during testing this PR? As comments to this PR?

**Comment by ferishili** [comment]
Hi @dagraf,
please make sure that you have the latest commit (https://github.com/opencast-ilias/OpenCast/pull/186/commits/96892839d600054b936103b6f45d43b17707d7b6) before testing!

**Comment by chfsx** [comment]
@dagraf i suggest to create issues with a new label „testing0822“ or something similar. additionally as @ferishili mentioned, we will push fixes tho this branch as well, therefore you should update the code on your testing installation maybe daily or more often if possible

**Comment by dagraf** [comment]
@ferishili and @chfsx: I will continue with testing (and probably finish it) on thursday. So I would suggest you push as many fixes as possible untill tomorrow evening and then let me test this version on thursday. How does this sound?

**Comment by chfsx** [comment]
@dagraf perfect, thanks in advance for testing!

**Comment by ferishili** [comment]
Hi @dagraf
I just merged and included the PR #180 changes (stated as suggestion) into this PR, so please rebase your fork.

**Comment by ferishili** [comment]
@dagraf 
I have added the changes related to #183 which was very small and is about signing the mp4 file in player url. Please rebase your fork.
I won't add more codes/changes, therefore from my side, you could start the testing.
Thanks in advance for testing

**Comment by dagraf** [comment]
I done with testing and detected only 2 issues (see bug reports). Unfortunately, I was not able to test our Tobira and Annotation Tool test cases because those are not installed on our Opencast we run for the community. As soon as we are finished testing other features on our other test installations we will test those cases. This will be not before the end of next week.

**Comment by dagraf** [comment]
I'm done with testing this PR and the bugfixes I could do on our community ILIAS connected to the community Opencast. What I could not test: annotation tool, Tobira connection, access granting via API
The rest looks good. From our point of view, this PR can be merged. @chfsx Do you agree and if so, could you merge this PR? And would it be best to make a new branch (i.e., ilias_7)?

**Comment by chfsx** [comment]
@dagraf Thanks for the testing and feedback! I also think that we can merge the PR now and release a new version afterwards. But iahc would wait with the renaming of the branch until we then also publish an ILIAS 8 version. From then on it makes sense to name the branches according to the ILIAS releases (release_7, release_8, ...). Is that ok?

**Comment by dagraf** [comment]
@chfsx Yes, sounds good. Thanks!

**Comment by dagraf** [comment]
@chfsx Could you merge this PR before our next community meeting tomorrow?

**Pull request merged**
