### PR TITLE
Rename OpenCast to OpencastObject

### PR DESCRIPTION
**Pull request by ebbertd**
Currently, the name `OpenCast` is used, which is wrong. Opencast is spelled without a capital c. As a new name I chose `OpencastSeries`, simply because displaying a series from Opencast is what this plugin does. I replaced all occurrences in text and filenames and tested it on our test system.

See issue #30 for a discussion on the topic.

Once this has been merged the repository can be renamed as well.

**EDIT: New name is: OpencastObject**

However, there are still some open questions:

- [x] How do we deal with the needed renaming of the folder the plugin is in?
- [x] How do we deal with the needed renaming in the database entry?
- [x] Which update procedure do we want to recommend?

### CODE REVIEW

**Comment by Amstutz** [comment]
This is really low on my prios list, see my comment in the ticket. I see that this is not nice for us devs to look at for the moment, however, in my list, there are items our users have to deal with, that are just higher up ;-).

Concerning your questions: I do not know. @okaufman can you check if you run into issues with those changes. If we have a list of issues, we might find (hopefully easy) ways to deal with them.

**Comment by mtneug** [comment]
As people switch to the community repo they probably already have to apply manual changes (change git remote etc.). So changing the name of the plugin folder at the same time would be ideal instead of doing it sometime later.

**Comment by Amstutz** [comment]
@mtneug : Good point!

Can you do some testing on the changes here and provide feedback if possible, especially to the questions of changes needed on the database (depending on the outcome of your tests)? It might also be just a list of issues you ran into, if any. Atm, I am not certain, if the logic here will trigger errors (is cases sensitive).

**Comment by ebbertd** [comment]
What I did was:

- deactivate the plugins
- pull in the changes
- rename the folder
- try to install the new version, which did not work
- at this point I had to database entries in `il_plugins`, one for `OpenCast` and one for `OpencastSeries`. I deleted the entry for `OpenCast`
- tried to install again, which worked
- re-activate the plugin and all settings and objects still worked

**Comment by Amstutz** [comment]
you will probably be left with some "data corpses" (Datenleichen) in the DB. However, since you will be routed to the new same plugin id, you might be fine.

So what would be needed here is an update step in the plugins sql file doing exactly what you did manualy (delete the one for Opencast). Do not forget, to also iterate the plugin version in the plugins sql after adding the db step. This will cause ILIAS to detect the change, deactivating the plugin and waiting for the update to be triggered through the GUIs Plugin Administration.

**Comment by DZenker** [comment]
But, inserting a series is not the only task of the plugin, because it also manages all communication with the Opencast API, on which the PageComponent plugin depends.

**Comment by ebbertd** [comment]
> But, inserting a series is not the only task of the plugin, because it also manages all communication with the Opencast API, on which the PageComponent plugin depends.

There already is a PR to also make the needed changes in the PageComponent. See: https://github.com/opencast-ilias/OpencastPageComponent/pull/6

**Comment by DZenker** [comment]
What I wanted to say is, that the "Opencast" plugin is a dependency for both the PageComponent and the event plugin, as it manages all communications with the Opencast API. Thus, a name like "OpencastSeries" would be somewhat misleading.

**Comment by ebbertd** [comment]
Now I understand your point. What about `OpencastObject`?

**Comment by DZenker** [comment]
Much better... ;-)

**Comment by ebbertd** [comment]
I just changed to renaming to `OpencastObject`.

@chfsx Should we include https://github.com/opencast-ilias/OpenCast/pull/35 in this PR?

**Comment by chfsx** [comment]
@ebbertd yes I think we should include the changes from #35. And I think we should have a solution for #39 as well before publish the new major which includes the renaming. I could provide a PR for #39 next week as well as for #36

**Comment by chfsx** [comment]
Thanks @ebbertd! I forgot we should check the version a user comes from (#39), could you implement that as well or shall I provide some lines for this?

**Comment by ebbertd** [comment]
> Thanks @ebbertd! I forgot we should check the version a user comes from (#39), could you implement that as well or shall I provide some lines for this?

@chfsx  I can't, so please do. You should be able to just push to this branch. I'll test it afterwards.

**Comment by reiferschris** [comment]
I wanted to test this PR again after all the bugfixes that were merged in the meantime but I now have trouble circumventing the RENAMIN_PLUGIN.md
Even though I went through all necessary and mentioned steps in my test system I cant update the plugin.
I renamed the DB entry, moved the directory with the correct name `OpencastObject` and did an `sudo composer dump-autoload` because otherwise it fails with a permission error.
Any ideas what could be causing that issue? @Amstutz @chfsx 

As to the conflicting files I'm not sure what github wants. When I apply this PR to the main branch I can't find any references to the old spelling `OpenCast` .

**Comment by Amstutz** [comment]
As discussed in the open cast community meeting today. I will close this since we consider the resources necessary to properly test and implement this are questionable due to the large amount of other issues that need fixing atm.

**Comment by reiferschris** [comment]
Another important consideration was that apparently the process of renaming is not as straightforward even with the implemented checks. We agreed that it would be nice to also fix the name in the code but that it is not worth potentially breaking production systems while doing so. If this process will be easier in future versions of ilias it could be reconsidered.

**Pull request closed without merging**
