### PR TITLE
[Release 8] Paella improvements

### LINKED ISSUE #289: Memorization of last position in video is not per video
**Describe the bug**
When leaving the Paella Player in the middle of a video, the last position is remembered. Unfortunately this position is not remembered per video, i.e. when playing **another** video afterwards it starts from the remembered position of the last one.

**To Reproduce**
1. Go to 'Play' for a video
2. The player with the thumbnail is visible. Now click the Play button.
3. Play some time, pause the video, remember the time stamp the video has stopped.
4. Leave video and open another one for playing.
5. The player with the thumbnail is visible. Now click the Play button.
6. The new video starts from the time position the previous one has been left.

**Expected behavior**
A new video should play right from the start resp. the position I left exactly this video the last time.

**Environment (please complete the following information):**
 - ILIAS version:  7.30
 - PHP version: PHP 7.4
 - Plugin version: 7.0.3 (May 2024)
 - Opencast version: 14.6.
 - Browser: Firefox, Chromium

**Note**
Until there is a solution a certain flag in the _config.json_ of the player should be set to false. Unfortunately I do not know which one, please someone else add this info!

### LINKED ISSUE #292: Too much unnecessary subtitle details in paella player
#### Description
The subtitle names in the ILIAS paella player shows unnecessary details of the captions (when they have tag details) devided by "-" e.g. `eng - (Manual) - (Subtitle) ` which does not match the Opencast paella player that only shows the language name!

**To Reproduce**
1. Make sure you have a video that has captions (subtitles) using new mechanism with tags
2. Play that video in ILIAS and check the caption name
3. Play that video in Opencast and check the caption name there

**Expected behavior**
The ILIAS paella player should provide only the language name just like paella player in opencast.

**Environment (please complete the following information):**
 - ILIAS version: v7 or v8
 - Plugin version: release_7 & release_8 are affected
 - Opencast version 15 (must)
 - Browser: all

### LINKED ISSUE #293: Download of video by a right click should not be possible
**Describe the bug**
With Paella 7, the videos can be downloaded using the right click and then "Save video". This should not be the case.

**To Reproduce**
1. Open a video
2. Make a right click
3. Choose "Save video as"

**Expected behavior**
It should not be possible to download the video that easily. Possible solution: The right click 

**Environment (please complete the following information):**
 - ILIAS version: v8.12 2024-05-28
 - Plugin version: 8.0.5
 - Opencast version: 15
 - Browser: Firefox

**Additional context**
It might be a solution, to make changes in paella-player.js (under: Prevent video download).

### LINKED ISSUE #294: Update Paella player user tracking plugin to support Matomo Media Analytics plugin
Recently some improvements have been made to the Paella player user tracking plugin. The changes make it possible to send player statistics data to the Matomo Media Analytics plugin. Therefore, the latest version 1.42.4 of paella-user-tracking should be integrated into the Opencast plugin.

### PR DESCRIPTION
**Pull request by ferishili**
This PR
fixes #289,
fixes #292,
fixes #293,
fixes #294

### New changes/additions/improvements
- Player configuration now has more unified and cleaner look, by putting options in sections
-  Player configuration now has 4 new options:
   - Prevent video download (#293)
   - Caption Text: Type, Generator, Generator Type (#292)
- Peall player dependency update: (#294)
  - paella-core: 1.48.2
  - paella-basic-plugins: 1.44.7
  - paella-slide-plugins: 1.41.4
  - paella-user-tracking: 1.42.2
  - paella-zoom-plugin: 1.41.3
- No more `restoreLastTime` (#289)

### To test
- Please make sure that your browser `cache` is clear.
- To test captions texts you would need Opencast 15 and auto generated subtitles!

Similar changes will be provided for release_7: https://github.com/opencast-ilias/OpenCast/pull/296

### CODE REVIEW

**Comment by snoesberger** [comment]
@ferishili regarding the Paella player dependency update, is it possible to go for paella-user-tracking version **1.42.4** instead of 1.42.2? As I mentioned in https://github.com/opencast-ilias/OpenCast/issues/294 some improvements have been made to the Matomo integration.

**Comment by ferishili** [comment]
Yes, of course, and sorry @snoesberger
I missed your suggested version!
Taking care of it right away.

**Comment by ferishili** [comment]
@snoesberger done!
(also for release_7)

**Comment by dagraf** [comment]
All tests were successfull. Therfore and @chfsx, can you please review the PR and merge it if everything is fine or comment it if otherwise. Thx!

**Pull request merged**
