### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by chfsx**
@ferishili, @dagraf and @reiferschris 

I merged the three PRs
- #215 
- #217 
- #222 

in this branch and resolved all conflicts. I cannot test the three features deeply, could you please have a look at this branch (code maybe @ferishili, testing @dagraf and @reiferschris )

I think this is the easiest way to merge those three PRs. the last (#229) will then be easy to adapt.

After merthis this PR here and the fixed version of #229, we are ready for our ILIAS8 lockdown.

This PR increases the plugin version to 5.6.0

### CODE REVIEW

**Comment by chfsx** [comment]
@ferishili of course you can open a PR against this branch (https://github.com/srsolutionsag/OpenCast/tree/staging) if you want to use the LocaleTrait now which has been merged already

**Comment by reiferschris** [comment]
I did a quick test with all the features and didn't encounter any issues. 👍

**Comment by ferishili** [comment]
I have provided the final PR against your repo, which completes this staging process.

**Comment by chfsx** [comment]
Thanks you very much for testing and all contributions!

**Pull request merged**
