### PR TITLE
[Release 8] Upload Subtitles

### LINKED ISSUE #10: Upload of subtitles
**Use Case**

Opencast can handle subtitles, these can be processed and displayed in the player. A subtitle editor is in development.

**Desired implementation**

The upload of subtitles should be possible during the initial video upload, as well as afterwards for already published videos. Currently, the Opencast API does not support this. This Opencast PR needs to be merged first: https://github.com/opencast/opencast/pull/3670

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #10

### Description
Users are now able to upload (one) subtitle file (with configured accepted file type) for each (configured) language together with uploading a video.
More info in the issue's description!

### Requirement
- Opencast 15 and above
- ILIAS 8
- Opencast Plugin (`release_8`)

#### Plugin Config (Admin side)
- A new (sub) Tab in plugin settings under Administration > Plugins > OpenCast > Settings > Subtitles is introduced.
- in subtitles setting page:
   - Subtitle Upload Activation toggle (Important)
      - admins have to select the subtitle file types from the list (Important)
      - admins have to add the supported languages (format: separated with "|||" e.g. eng|||English) (Important)
      - It is also possible to get the languages list from the list provider API directly from Opencast.
#### User side
- In upload form users are now able to see  a new section called "Subtitles" containing a list of (single) file upload blocks for each configured language.

### Subtitle Conversion
Due to the fact that, Opencast 15 handles Subtitles as first class citizens ([more info](https://github.com/opencast/opencast/issues/4407)), by default Opencast looks for and processes WebVTT formats, therefore, we need to simply convert other formats to VTT using FFmpeg!
#### In Opencast (not possible)
It is possible to convert to VTT using FFmpeg in Workflows (partial-ingest) using encode operation, however, as we have to also pass Tags and work with tags, it is currently a **limitation in Opencast** by which workflow operations **cannot** copy tags over from one track to another. (I could not find any way, if you know such way please let me know!)
#### In ILIAS (possible and included)
In order for this to happen in ILIAS, one must install FFmpeg and configure it in ILIAS ([Optional Dependencies for ILIAS](https://docu.ilias.de/ilias.php?baseClass=illmpresentationgui&cmd=resume&ref_id=367)).

**NOTE:** This PR may receive further updates!
Your feedback and opinions are very welcome.

**NOTE:** This depends on #299, for passing workflow params to ingest!

### CODE REVIEW

**Comment by dagraf** [comment]
**Bug: Workflow parameter "straightToPublishing" has no effect when the upload of subtitles is activated in the config**

Steps to reproduce:
1. Have the option "Enable Subtitle Upload" activated.
2. Have the Workflow Parameter "straightToPublishing" configured as "Show in Form (checkbox selected" (Usage for Admins, Title "Automatisch publizieren").
3. Upload a video and leave the option "Automatische publizieren" deactivated.
4. See error: The video does not get published (because the workflow parameter for straightToPublishing is set to 'false' in Opencast.

**Comment by dagraf** [comment]
> **Bug: Workflow parameter "straightToPublishing" has no effect when the upload of subtitles is activated in the config**
> 
> Steps to reproduce:
> 
>     1. Have the option "Enable Subtitle Upload" activated.
> 
>     2. Have the Workflow Parameter "straightToPublishing" configured as "Show in Form (checkbox selected" (Usage for Admins, Title "Automatisch publizieren").
> 
>     3. Upload a video and leave the option "Automatische publizieren" deactivated.
> 
>     4. See error: The video does not get published (because the workflow parameter for straightToPublishing is set to 'false' in Opencast.

The new commits fixed this issue.

**Comment by dagraf** [comment]
Our testings were all successfull. We tested with srt- and vtt-files and with german, english and french subtitles. Everything worked as expected.
@ferishili or @chfsx: Should we now take care of merging this PR which brings in a new feature or would you recommend us to wait for testresults of the remaining new features and publish a new version of the plugin?

**Comment by dagraf** [comment]
@chfsx: Could you please review this PR?

I then would like to discuss how to proceed with the PRs that introduce the new features in our next community meeting.

**Review by chfsx — APPROVED** [review]
Thanks a lot, as in #301 I did several small changes while squashing this PR, but it was only nitpicking and code-style.

**Comment by chfsx** [comment]
Merged in v8.1.0

**Pull request closed without merging**
