### PR TITLE
Fix german translation typos and add missing translations

### PR DESCRIPTION
**Pull request by Hufschmidt**
Just a fix for a minor translation issue, see commit itself for details.

### CODE REVIEW

**Review by ferishili — APPROVED** [review]

**Comment by dagraf** [comment]
@chfsx: Since @ferishili approved this PR, I guess you will merge it in the following days. Right?

**Comment by chfsx** [comment]
Thanks a lot @Hufschmidt, I cherry-picked the changes to release_8 as well

**Comment by rfcmaXi** [comment]
Service note: The json is not read out live or interpreted accordingly. In this respect, the fix is correct, but has no effect. The changes made by @Hufschmidt therefore had to be written directly into the corresponding player js files. This is not very nice and I don't know if this is what you want here...

**Comment by Hufschmidt** [comment]
> Service note: The json is not read out live or interpreted accordingly. In this respect, the fix is correct, but has no effect. The changes made by @Hufschmidt therefore had to be written directly into the corresponding player js files. This is not very nice and I don't know if this is what you want here...

Interesting, my assumption was that this would happen when rebuilding the included paella player using the given [rollup config](https://github.com/opencast-ilias/OpenCast/blob/release_7/js/opencast/rollup.config.js).

**Pull request merged**
