### PR TITLE
Implemented new Chunked Upload

### PR DESCRIPTION
**Pull request by chfsx**
This is an implementation of a new ChunkedFile-UI\Input which should solve #27

https://user-images.githubusercontent.com/6661332/184369155-bc5a2e25-574c-4061-9293-c0b69bcd7271.mov

My setup has a 200MB upload-limit, with the Chunked-Upload the form can handle Files up to 5GB (we should implement a setting for that value).

Feedback is highly appreciated and the PR need some testing (I tested on ILIAS 7)

### CODE REVIEW

**Comment by chfsx** [comment]
ILIAS 6 should work now as well

**Comment by okaufman** [comment]
Thank you very much for this PR. 
I ran into a problem when testing this on my setup. 
After selecting a file and waiting until the bar is fully loaded, I get the message "Please Upload a file." when I click on save. The file does not get uploaded to the series and there is no error in the ilias.log or the curl.log

I am using ilias 7.12 and php 7.4

**Comment by chfsx** [comment]
Thanks for the feedback @okaufman, I try to reproduce this as well and will give you feedback ASAP

**Comment by okaufman** [comment]
Thank you for the quick fixes. They solved my problem.

**Comment by dagraf** [comment]
> My setup has a 200MB upload-limit, with the Chunked-Upload the form can handle Files up to 5GB (we should implement a setting for that value).

I highly agree to make "Maximum upload size" configurable. I would suggest to insert this new option in the tab "Settings" > subtab "Events". Does it need a specific explanation on how to set this upload-limit properly?

**Comment by dagraf** [comment]
After some testing of the upload I have some suggestions on how to improve the upload:

1. Bug: When I selected a file and the progress bar indicates that the upload is finished, I then hit on save without having specified a title, ILIAS tells me that the title is missing (which is fine). The problem is, that the file seems to be lost (no longer listed in the section "File"). When I then try to upload the file again (via drag and drop) ILIAS tells me "You can not upload any more files" (see screenshot). Suspected solution: When the title is missing and a users hits on save the uploaded videos should still be indicated.
2. Improvement: When I upload a pretty large video it takes some time from hitting "Save" to showing me the tab "Content" again (on the our Community-ILIAS: approx. 15sec for a 500MB video). Would it be possible to tell the user in a more obvious was that ILIAS/Opencast is working in order to prevent them to aboard the ongoing process? For example we could use the same "turning wheel" that gets shown when opening a Opencast Series in ILIAS.
3. Improvement: Add a "Cancel" button next to the "Save" button.
4. Nice-to-have: Rename the "Save" button to "Upload Event" (DE: "Aufzeichnung hochladen")

Bildschirmfoto 2022-08-18 um 12 21 29

**Comment by chfsx** [comment]
Hi @dagraf and thanks for testing! I just committed:
- A fix for already existing files (after sending without a title, your Bug)
- A config for the upload limit, see screenshot

Bildschirmfoto 2022-08-18 um 15 54 49

A cancel-button is not possible since the new UI\Form doesn't support more than one button. and this button (at least in ILIAS 6/7 can't be renamed and is always labeled with "Save"

**Comment by dagraf** [comment]
Thanks for the fix and the comment about labeling of buttons.

We have some new issues after the fix:

- Config: Please move the new config to the subtab "Events" (as stated above) and there right below config "Processing Workflow ID".
- New bug: Now the upload does not work anymore. If I try to upload a video ILIAS shows me this error screen:
MicrosoftTeams-image (4)

**Comment by okaufman** [comment]
The error "Call to undefined Method.." occurs because the file-input can't handle the constraint withRequired(true). It was added with this  commit in the EventFormBuilder.php. ( https://github.com/opencast-ilias/OpenCast/pull/66/commits/db9aff9a2f99fdb521fe988d5144f046b6f3113b)
This Problem is also mentioned in this ILIAS-Mantis-Issue: https://mantis.ilias.de/view.php?id=31645 

After removing this part in the code the Bug mentioned by David still persists. When a user tries to upload a file without a proper title, the file no longer appears after hitting "save". And it is not possible to upload a new file.

**Comment by chfsx** [comment]
Hi @okaufman I already have some changes in the pipeline which will fix that.

**Comment by chfsx** [comment]
Hi @okaufman and @dagraf I pushed the latest changes which will
- move the setting to the Events-Subtab
- fix the upload

**Comment by okaufman** [comment]
Thank you very much. The error now no longer appears. 
When I try to upload a video without a title and the in a second step try to upload the same video with a title, I still have a problem. The video appears on the GUI in the second step but when I click save, I get a message saying, I havent yet uploaded a video.
I made a video to illustrate the problem:

https://user-images.githubusercontent.com/41621260/187389582-26ebda65-cea4-413e-8b9f-bf4cf8c071d1.mov

**Comment by chfsx** [comment]
thanks for the video, i could reproduce and hopefully fix the big now. please try once with a file smaller than your upload limit (from php) and once with a larger file

**Comment by chfsx** [comment]
and I managed to make the fileinput required now

**Comment by okaufman** [comment]
Thank you very much. This solved my problems.

**Comment by dagraf** [comment]
I can confirm. The upload works now as expected. 

But I would strongly suggest to alter the option to set the upload limit in a way, that the the maximum upload size gets indicated in a more often used way (I had to google "MiB, too), using 'regular' MB. Like this we would be closer to how it is indicated in ILIAS (see upload limit for "Files") and also how sizes get indicated on users computers. Because with MiB I expect our teachers to be wondering:  What are "MiB"? Is this a spelling mistake and should it actually be MB? Should I google it?

What do you think, @chfsx ?

**Comment by chfsx** [comment]
@dagraf you are right, MB is definitely more "readable" and easier to understand, I changed that in my latest commit

**Comment by chfsx** [comment]
Hi @reiferschris! thanks for testing, I hope we will find the issue soon... some word to the general behaviour:
- ILIAS has no setting for the upload limit, only the values from php are used (the smaller value of post_max_size or upload_max_filesize
- The chunked upload here uses half the size of the configured (php) upload limit as chunk size. I think this leads to the size of your chunks: 256*1024*1024/2*1000*1000
- you should see several POSTs during the upload in your console, one POST per chunk which is sent

it seems as if the last chunk fails, is there a HTTP/500 in one of those requests? maybe you can filter your js-console for XHR-requests only

**Comment by chfsx** [comment]
@reiferschris maybe you can pull the latest commit which does the chunk size calculation better...

**Comment by reiferschris** [comment]
Hi @chfsx I tested again with your latest commit and the issue disappeared. Thank you!

**Comment by Amstutz** [comment]
We tested that throughly and did not pick up any further issues. Thx for improving the language variable as suggested by @dagraf . We will merge this. Thx to everybody involved.

kindly
@Amstutz and @okaufman

**Pull request merged**
