### PR TITLE
[FIX] Memory Limit Issue with large files to upload

### PR DESCRIPTION
**Pull request by chfsx**
This fixes the memory limit issue in #220

### CODE REVIEW

**Comment by reiferschris** [comment]
I did a test with a 2GB file and the upload worked.
The "save"-Button however was not disabled immediately like before. The "spinner" animation that previously block any more user interaction only showed up briefly, when the process was almost done.

**Comment by dagraf** [comment]
@marcusm7: Did you make the same observation as @reiferschris ("Save"-Button does not get disabled immediately when clicking on "Save") during your tests?

**Comment by marcusm7** [comment]
https://github.com/opencast-ilias/OpenCast/issues/220#issuecomment-1819275958

In my case the 'Speichern' button is disabled until the upload of the 10G file is completed (as before). After click on 'Speichern' the spinner animation is shown until the ingest is completed (as far as I can tell,the spinner-animation was there for a some seconds, while the fpm-worker generated some cpu load.). But I don't want to contradict @reiferschris - I just did a very quick test.

**Comment by dagraf** [comment]
I make the same observation as described here (https://github.com/opencast-ilias/OpenCast/pull/221#issuecomment-1819274532). But the same is true for the plugin v5.1.1 that is running on our productive ILIAS. Therefore and @chfsx: Could you please have a short look into it if there would be a quick solution to disable user interactions as soon as a user hits on "Save"? Thank you.

**Comment by chfsx** [comment]
Thank you for testing! yes, the overlay was not displayed at the right time before. i have now implemented this, rebuilt the JavaScript for the overlay and made some optimizations for the future.

**Comment by chfsx** [comment]
The PR updates the plugin to version 5.3.2

**Comment by dagraf** [comment]
Thx for the update. I can confirm that the spinning wheel overlay gets displayed right after clicking on "Save" and that upload of large files works now.

Therefore, and @Amstutz: Can you please review this PR and comment it if needed or merge it? Thx!

**Comment by Amstutz** [comment]
Thx for removing the static functions and for adding the JS class!

**Pull request merged**
