### PR TITLE
Fix Several Issues (8)

### PR DESCRIPTION
**Pull request by chfsx**
This PR proposes a new Version 8.0.2 and fixes the issues:
- https://github.com/opencast-ilias/OpenCast/issues/249
- https://github.com/opencast-ilias/OpenCast/issues/250
- https://github.com/opencast-ilias/OpenCast/issues/251
- https://github.com/opencast-ilias/OpenCast/issues/252
- https://github.com/opencast-ilias/OpenCast/issues/254

### CODE REVIEW

**Comment by chfsx** [comment]
A ILIAS 7 version of this PR will follow soon

**Comment by chfsx** [comment]
PR #257 in included here

**Comment by dagraf** [comment]
All bugfixes were successfully tested and approved. 
Therefore, @Amstutz: Can you please review this PR and either comment or merge it? Thx!

**Comment by Amstutz** [comment]
Hi @chfsx 

Thx for the PR. Special thx for adding strict types in several places, the release notes and the comment in the update file. 

If possible, split PRs (make them smaller) somewhat, to make it easier to reviews. However, I do understand, why you packed several in this single PR. 

thx

**Comment by chfsx** [comment]
Hi @Amstutz I packed changes in separate commits, maybe its easier to follow them.

**Pull request merged**
