### PR TITLE
Opencast PHP Library Upgrade (v.1.6.0) / release_8

### LINKED ISSUE #272: Opencast PHP Library Upgrade (v.1.6.0)
As an upgrade announcement:

There is a new version of Opencast PHP Library (v.1.6.0), which contains Playlist Endpoints and necessary changes in Ingest endpoint.
Please take a look at the release:
https://github.com/elan-ev/opencast-php-library/releases/tag/1.6.0

PR for both releases will follow.

NOTE: v1.6.0 has important changes for Subtitles Upload #10

### PR DESCRIPTION
**Pull request by ferishili**
This PR contains the upgrade of oc-php-lib to v1.6.0 for release_8
This fixes #272 
Refer to issue's description

### CODE REVIEW

**Comment by ferishili** [comment]
Hi @Amstutz, Hi @chfsx,
I would like to ask for an urgent review and merge of this PR, in order for me to finish the implementation of Subtitle.

Thanks in advance

**Comment by chfsx** [comment]
hi @ferishili 
thanks for updating the library! the PR seems fine from my point of view. I'm not sure wether this need some testing from an institution before?

**Comment by Amstutz** [comment]
Since we change the lib I would certainly like to have this tested before merging. Does this change also need a downpick to 7?

**Comment by ferishili** [comment]
Hi @chfsx, hi @Amstutz,
thanks for the feedback, testing is always good and because the new included changes do not affect the current functions we are already using, therefore, a simple test of major functionalities of the plugin like (upload, edit metadata, etc.) would be enough.

And for the release_7, I have already provided the same [PR for release 7](https://github.com/opencast-ilias/OpenCast/pull/274) as well, so there is no need to downpick this PR to 7!

**Comment by Amstutz** [comment]
+1, for a small set of sanity tests would suffice. thx for the PR for 7. IMO 7 and 8 should be close enough, that tests only on 8 should do. @dagraf , can you do this?

**Comment by dagraf** [comment]
I will do santy tests this afternoon and report the results here.

**Comment by dagraf** [comment]
Initial testing revealed some issues. We are checking now the cause of this issue. More information will follow tomorrow.

**Comment by dagraf** [comment]
The initial problem could be solved. All sanity tests were succesfull. @Amstutz, can you take over and merge this and the PR for 7?

**Pull request merged**
