### PR TITLE
[Release 8] disable restorePlaybackRate feature for livestreams

### LINKED ISSUE #302: Paella Player default config `restorePlaybackRate` also applies to livestreams
**Describe the bug**
Paella Player default config `"restorePlaybackRate": true` also applies to livestreams which leads to stutters in playback when the livestream reaches "live" and is not catching up to "live"

**To Reproduce**
1. Go to a VOD-Video, change playback rate to something other than 1.0x
2. Go watch a livestream "live"
3. Observe playback stutter caused by the restored playback rate from the VOD

**Expected behavior**
The livestream plays smoothly (without a previously set playback rate), ideally it disables

**Additional context**
It would be nice to have the option to enable playback rate changes for buffered parts of a livestream but to automatically change back to 1.0x speed when reaching "live"

### PR DESCRIPTION
**Pull request by reiferschris**
Version for branch release_8
Closes https://github.com/opencast-ilias/OpenCast/issues/302
Please see Issue for details

### CODE REVIEW

**Review by snoesberger — CHANGES_REQUESTED** [review]
Thanks @reiferschris

I have tested this and it works fine for unbuffered livestreams. But if you have enabled "Buffered Livestreams" in the live stream settings, the Paella player will load `opencast_live_buffered_theme.json` instead of `opencast_live_theme.json`. Therefore, the change made in `opencast_live_theme.json` must also be made in `opencast_live_buffered_theme.json`.

**Comment by dagraf** [comment]
@reiferschris: What do you think about @snoesberger last comment? Is the suggested change something you can agree to?

**Comment by reiferschris** [comment]
@dagraf @snoesberger sorry I somehow missed this. I pushed the fix also for buffered livestreams.
Edit: since I don't have buffered livestreams like you do, I can't properly test this so it's up to you to confirm :)

**Comment by snoesberger** [comment]
> Edit: since I don't have buffered livestreams like you do, I can't properly test this so it's up to you to confirm :)

Thanks @reiferschris! I can confirm that now it also works for buffered live streams.

**Comment by dagraf** [comment]
Thx for testing. Since they were successfull: @ferishili, can you please prepare this PR for merging and pass it over to @chfsx for a review? Thx!

**Comment by ferishili** [comment]
@reiferschris, would you merge the latest changes from `release_8` branch to this PR, since you created it?

**Comment by dagraf** [comment]
@ferishili: Since @reiferschris is ill at the moment and we need this PR to be merged tomorrow, can you please do the above mentioned merging today? That would be great.

**Comment by chfsx** [comment]
Thanks a lot, merged to v8.1.4!

**Pull request merged**
