### PR TITLE
Fix Several Issues (7)

### PR DESCRIPTION
**Pull request by chfsx**
This is the ILIAS 7 version of PR #255 and fixes

- https://github.com/opencast-ilias/OpenCast/issues/249
- https://github.com/opencast-ilias/OpenCast/issues/250
- https://github.com/opencast-ilias/OpenCast/issues/251
- https://github.com/opencast-ilias/OpenCast/issues/252
- https://github.com/opencast-ilias/OpenCast/issues/254

### CODE REVIEW

**Comment by chfsx** [comment]
PR #257 in included here

**Comment by reiferschris** [comment]
Thank you so much for fixing all the issues!
I can confirm that updates from versions prior to 5.6  as well as from 5.6. to `release_7` now work as expected. The db fields that where wrong are now correct :)

Also importing/exporting works now.

I now have no objections to deleting the main-branch anymore.

**Comment by reiferschris** [comment]
Hi @chfsx @dagraf 
can this be merged? Should I just do it?

**Comment by dagraf** [comment]
All bugfixes were successfully tested and approved.
Therefore, @Amstutz: Can you please review this PR and either comment or merge it? Thx!

**Comment by Amstutz** [comment]
See comment in: https://github.com/opencast-ilias/OpenCast/pull/255

**Pull request merged**
