### PR TITLE
[Release 8][Fix] Escape non-strings in prefill replacement

### LINKED ISSUE #263: Release 8: error when adding new series object to a course with prefilled metadata
**Describe the bug**
When you add prefill placeholders to series metadata and try to add a series object to a course, a fatal error occurs stating that `str_replace` must always get string values!

**To Reproduce**
1. Have a clean installation of release_8 with PHP 8!
2. Go to Plugin Configs > Metadata > Series
3. Try to add prefill to the title with: `[COURSE.REF_ID]`
4. Save changes.
5. Go to a course and try to add a new Opencast Series Object.
6. See the error!

**Expected behavior**
Prefill must be working in any cases!

**Log**
```
[b128o] [2024-03-28 08:16:28.778737] ilias_8_root.ERROR: Whoops\Handler\CallbackHandler::handle:398 0 str_replace(): Argument #2 ($replace) must be of type array|string, int given in /release_8/src/Model/Metadata/Helper/MDPrefiller.php:207#0 /release_8/src/Model/Metadata/Helper/MDPrefiller.php(207): str_replace('[COURSE.REF_ID]', 83, 'Opencast Test C...')
#1 /release_8/src/UI/Metadata/MDFormItemBuilder.php(109): srag\Plugins\Opencast\Model\Metadata\Helper\MDPrefiller->getReplacedPrefill('[COURSE.TITLE] ...')
```

**Environment (please complete the following information):**
 - ILIAS version: v8.10
 - PHP version: 8.0.30
 - Plugin version: release_8
 - Opencast version 15.3
 - Browser: Firefox

**Additional context**
Did not check for release_7, however I think this is a PHP 8 strict error handler that causes the fatal error!

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #263 

### Description
please refer to issue.

### Solution
adding a string type casting solves the problem!

### CODE REVIEW

**Review by chfsx — APPROVED** [review]
LGTM, thanks @ferishili !

**Comment by dagraf** [comment]
Tests of this PR were successfull. Therefore and @Amstutz: Can you please review this PR and comment or merge it, depending on your results? Thank you!

**Comment by Amstutz** [comment]
thx a lot looks good. however, how did you decide on merging things like this down to 7? Do we merge does things down, even if no strictly required?

**Comment by Amstutz** [comment]
In a short chat with @chfsx we decided to pick this to 8 as well.

**Pull request merged**
