### PR TITLE
Delete unused datetimepicker library

### PR DESCRIPTION
**Pull request by mliradelc**
This PR deletes the unused library `datetimepiker`

### CODE REVIEW

**Comment by mliradelc** [comment]
@theodortruffer Can you confirm that the library not in use anymore? 

I figure out since this commit the plugin is not called  https://github.com/fluxapps/OpenCast/commit/6bbaa3cafd06e5091bf6d83e0c5096e2b3460b59

**Comment by ebbertd** [comment]
This would close #38

**Comment by Amstutz** [comment]
Thx a lot for taking care of this. We cannot directly merge this, since we do have a conflict. @okaufman will resolve this locally and then push.

**Comment by Amstutz** [comment]
Commit: https://github.com/opencast-ilias/OpenCast/commit/34fb2dc416f7f661b8bfd9dfa185751904f69f9a

**Pull request closed without merging**
