### PR TITLE
Paella dependabot bumps

### PR DESCRIPTION
**Pull request by ferishili**
this PR consists of two dependabot bumps with a local rebase performed, and luckily there is no changes to the outputs.

By merging this #227 & #226 could be rebased or closed!

### CODE REVIEW

**Comment by chfsx** [comment]
did you perform a $ npm clean-install ?

**Comment by ferishili** [comment]
`npm clean-install `& `npm run build` has been performed

**Comment by chfsx** [comment]
strange… i‘m pretty sure there mist be changes in the js files of those dependencies 🤔 because a lot of version changes happen

**Comment by ferishili** [comment]
It was mostly about postcss and we have no css in there needed to be complied!

**Comment by chfsx** [comment]
Ah I see, we do not deliver the node_modes folder with the plugin. which is good in general, but do ILIAS admins know they have to install it here?

**Comment by ferishili** [comment]
Admins don't need to install anything, because everything needed has been build and put into `paella-player.min.js`

Only when one wants to develop something by which he/she has to perform `npm install` and `npm run dev` or `npm run build` anyway!

**Comment by chfsx** [comment]
very nice, I haven't realized that yet :-)

**Pull request merged**
