### PR TITLE
[Release 8] OCT Text feature

### LINKED ISSUE #271: OCR-Text
This is a feature request to bring OCR-Text support into ILIAS.

This issue will be updated shortly.

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #271,

### Description
In Opencast Paella Player there is a feature known as Transcriptions or Text search, by which user can look up for the text extracted from the segments and select the and navigate to specific segment of the video.
The text extraction must be configured in Opencast in order for it to extract and to provide the texts, known as MPEG7 Texts. please have take a look at [Opencast Documentation](https://docs.opencast.org/r/15.x/admin/#configuration/textextraction/#text-extraction-configuration)
With this PR, the Paella Player Transcription feature is now possible to be provided also in ILIAS.

#### Configuration: (Plugin Configuration)
- `Settings > Player > Enable OCT Text feature`:  there is a new option unser settings > player, called "Enable OCT Text feature" with needs to be activated.
- `Publications > Add new >  MPEG7 Catalog` : A new publication usage is introduced to read the MPEG7 Catalog texts:
    - Channel: `engage-player`
    - Type: `Metadata`
    - Flavor: `mpeg-7/text`
    - Mediatype: `text/xml`

- NOTE: in order for this feature to work both above mentioned configurations are required!

#### Paella Player
- Open a video that has OCT Text already processed and provided.
- `Settings > Transcription`: The transcription button is now under settings on the right hand side!

(Screenshot is from the Opencast Paella Player, therefore, the items placement and looks may vary from the ILIAS Paella player)
Screenshot_GitHub

### To test
- ILIAS 8
- Preferably Opencast 15
- you would need Text extraction ready in Opencast
- A video must have already been processed and finished with text extraction workflow operation.
- This PR must be already patched and ready.
- Configurations mentioned above!
- Open that video in a Series Object Repository in ILIAS.
- Navigate to the Transcription button in paella player.
- Look for a text and navigate to differernt segment => video mus jump to that timepoint!
- (Try all possible letter + CAPITAL, normal letters etc.)

### CODE REVIEW

**Comment by tscheere** [comment]
We tested this and it works.

ILIAS version: (v8.12 2024-05-28)
PHP version: [PHP 7.4.33]
Plugin version: [8.0.3]
Opencast version [15.5.0]
Browser: [chrome]

**Comment by ferishili** [comment]
Thank you @tscheere,
@dagraf what would be the next step?

**Comment by dagraf** [comment]
@chfsx: Could you please review this PR? 

I then would like to discuss how to proceed with the PRs that introduce the new features in our next community meeting.

**Comment by ferishili** [comment]
Hi @chfsx,
An issue with keyboard shortcuts has been found for this PR. Please wait for the fix.
I am going to take care of it right away.
Thanks

**UPDATE:** The fix is there, please proceed

**Comment by ferishili** [comment]
This PR is successfully tested according to: https://github.com/opencast-ilias/OpenCast/pull/290#issuecomment-2173309714

@tscheere would you please test/confirm that the latest change request (keyboard shortcuts) is working fine?

**Comment by tscheere** [comment]
@ferishili yes, the issue with the keyboard shortcuts has been resolved and it works fine now. Thank you!

**Review by chfsx — APPROVED** [review]
and the last one, same here, some small changes, then squashed and prepared for new release (which will follow asap)

**Comment by chfsx** [comment]
Merged in v8.1.0

**Pull request closed without merging**
