### PR TITLE
Feature/7/general refactoring

### PR DESCRIPTION
**Pull request by chfsx**
This PR contains all adjustments in the plugin code that are necessary as a basis for the following ILIAS 8 version, but are still compatible with ILIAS 7, i.e. this branch must be tested with ILIAS 7, if everything is good, this new new version v7.0.0 will be released on a new branch release_7.

### CODE REVIEW

**Comment by chfsx** [comment]
@dagraf I forgot to mention you here

**Comment by reiferschris** [comment]
Thanks for all of this work. When trying to update from the previous main to this version I (still) get errors about trying to migrate from an incompatible version. So something is still not quite right when updating an existing installation.
I checked out your PR onto the current main branch with this  `git pull -X theirs upstream pull/236/head:refactoring-7` to avoid running into the conflicts. Is there a better way to do this? :)

```
ilPluginException thrown with message "You try to update from a incompatible version of the plugin, please read the infos here: https://github.com/opencast-ilias/OpenCast/blob/main/doc/migration.md"

Stacktrace:
#9 ilPluginException in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilOpenCastPlugin.php:63
#8 ilOpenCastPlugin:beforeUpdate in /var/www/html/Services/Component/classes/class.ilPlugin.php:1077
#7 ilPlugin:update in /var/www/html/Services/Component/classes/class.ilObjComponentSettingsGUI.php:507
#6 ilObjComponentSettingsGUI:update in /var/www/html/Services/Component/classes/class.ilObjComponentSettingsGUI.php:502
#5 ilObjComponentSettingsGUI:updatePlugin in /var/www/html/Services/Component/classes/class.ilObjComponentSettingsGUI.php:123
#4 ilObjComponentSettingsGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /var/www/html/Services/Administration/classes/class.ilAdministrationGUI.php:246
#2 ilAdministrationGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/html/ilias.php:23
```

**Comment by reiferschris** [comment]
When adding a new Opencast object in ILIAS the creation fails 

I think this happens because the course admin role has no default permissions for the opencast object configured. Previously this did not lead to an error.
```
TypeError thrown with message "Argument 1 passed to ilObjOpenCastAccess::getProducersForRefID() must be of the type int, string given, called in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOp
enCastGUI.php on line 392"

Stacktrace:
#11 TypeError in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastAccess.php:337
#10 ilObjOpenCastAccess:getProducersForRefID in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:392
#9 ilObjOpenCastGUI:afterSave in /var/www/html/Services/Object/classes/class.ilObjectGUI.php:1038
#8 ilObjectGUI:saveObject in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:364
#7 ilObjOpenCastGUI:save in /var/www/html/Services/Repository/classes/class.ilObjectPluginGUI.php:149
#6 ilObjectPluginGUI:executeCommand in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:188
#5 ilObjOpenCastGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#4 ilCtrl:forwardCommand in /var/www/html/Services/Repository/classes/class.ilRepositoryGUI.php:375
#3 ilRepositoryGUI:show in /var/www/html/Services/Repository/classes/class.ilRepositoryGUI.php:337
#2 ilRepositoryGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/html/ilias.php:23
```
When adding permissions (Edit Videos) to the course admin via the ilias role administration I get another error 
```
TypeError thrown with message "Return value of ilObjOpenCastListGUI::getOpenCast() must be an instance of srag\Plugins\Opencast\Model\Object\ObjectSettings, null returned"

Stacktrace:
#21 TypeError in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastListGUI.php:122
#20 ilObjOpenCastListGUI:getOpenCast in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastListGUI.php:138
#19 ilObjOpenCastListGUI:getCustomProperties in /var/www/html/Services/Object/classes/class.ilObjectListGUI.php:1689
#18 ilObjectListGUI:determineProperties in /var/www/html/Services/Object/classes/class.ilObjectListGUI.php:1801
#17 ilObjectListGUI:insertProperties in /var/www/html/Services/Object/classes/class.ilObjectListGUI.php:3462
#16 ilObjectListGUI:getListItemHTML in /var/www/html/Services/Container/classes/class.ilContainerContentGUI.php:707
#15 ilContainerContentGUI:renderItem in /var/www/html/Services/Container/classes/class.ilContainerSessionsContentGUI.php:176
#14 ilContainerSessionsContentGUI:__showMaterials in /var/www/html/Services/Container/classes/class.ilContainerSessionsContentGUI.php:105
#13 ilContainerSessionsContentGUI:getMainContent in /var/www/html/Services/Container/classes/class.ilContainerContentGUI.php:297
#12 ilContainerContentGUI:getCenterColumnHTML in /var/www/html/Services/Container/classes/class.ilContainerContentGUI.php:200
#11 ilContainerContentGUI:setOutput in /var/www/html/Services/Container/classes/class.ilContainerGUI.php:625
#10 ilContainerGUI:renderObject in /var/www/html/Modules/Course/classes/class.ilObjCourseGUI.php:184
#9 ilObjCourseGUI:viewObject in /var/www/html/Modules/Course/classes/class.ilObjCourseGUI.php:2746
#8 ilObjCourseGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#7 ilCtrl:forwardCommand in /var/www/html/Services/Repository/classes/class.ilRepositoryGUI.php:375
#6 ilRepositoryGUI:show in /var/www/html/Services/Repository/classes/class.ilRepositoryGUI.php:337
#5 ilRepositoryGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#4 ilCtrl:forwardCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:178
#3 ilCtrl:callBaseClass in /var/www/html/ilias.php:23
#2 include in /var/www/html/Services/Object/classes/class.ilObjectGUI.php:2069
#1 ilObjectGUI:_gotoRepositoryNode in /var/www/html/Modules/Course/classes/class.ilObjCourseGUI.php:2869
#0 ilObjCourseGUI:_goto in /var/www/html/goto.php:189
```

**Comment by reiferschris** [comment]
Another error occurs when trying to export plugin settings
```
TypeError thrown with message "DOMElement::__construct() expects parameter 2 to be string, int given"

Stacktrace:
#15 TypeError in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Config/PluginConfig.php:421
#14 DOMElement:__construct in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Config/PluginConfig.php:421
#13 srag\Plugins\Opencast\Model\Config\PluginConfig:getXMLExport in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/Export/class.xoctConfExportGUI.php:66
#12 xoctConfExportGUI:export in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:72
#11 xoctGUI:performCommand in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:66
#10 xoctGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#9 ilCtrl:forwardCommand in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctMainGUI.php:120
#8 xoctMainGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#7 ilCtrl:forwardCommand in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilOpenCastConfigGUI.php:75
#6 ilOpenCastConfigGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#5 ilCtrl:forwardCommand in /var/www/html/Services/Component/classes/class.ilObjComponentSettingsGUI.php:113
#4 ilObjComponentSettingsGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /var/www/html/Services/Administration/classes/class.ilAdministrationGUI.php:246
#2 ilAdministrationGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/html/ilias.php:23
```
I hope that feedback like this is at least a bit helpful and not annoying ;)

**Comment by reiferschris** [comment]
Hi, I started testing the updates to this PR and found a first issue:
In the Settings > Event > Chunk Size in MB Setting it says:
```
Chunk size in MB *
Value too high. Please enter a lower value.
Minimum Value: 1, Maximum Value: 0
```
As a result you can't enter a valid input anymore 😇

**Comment by dagraf** [comment]
At all: Manuel Wizgall (from University of Tübingen) has done some testing (and will continue to do so) on the Community platforms and has encountered some issues (see the Google-Sheet «[Test Run: Opencast-Plugin ILIAS7 Community-ILIAS PR236_20240125](https://docs.google.com/spreadsheets/d/151VND97ZZwIKg-RoF07T9ePdRGoZvev6/edit?usp=sharing&ouid=114782756758277767446&rtpof=true&sd=true)».

@chfsx: Can you have a look at the issues (see column "Gefundene Probleme") and fix them if possible? Thx! Please let me know on which contract (PHP8 or '2024 Dienstleistungsvertrag') you booked the hours spent.

**Pull request merged**
