### PR TITLE
[Release 8] Avoid unnecessary ACL update when updating series metadata

### PR DESCRIPTION
**Pull request by ferishili**
This PR refs #297,
Please refer to the description of #321, as it is only the release_8 of that PR

### CODE REVIEW

**Comment by dagraf** [comment]
Short question: Will we have no ACL update at all when updating series metadata after this PR? Because we once decided to integrate an ACL update when updating series metadata in order to have a step where changes of admins of an ILIAS course get passed to the series on Opencast.

**Comment by ferishili** [comment]
The series ACL update to Opencast only happens when there is a change to the ACL set!
So, to make sure that happens and works correctly, you would need to change ACLs in ILIAS (I think it could be achieved by changing PermissionTemplate!) and then update metadata.

**Comment by reiferschris** [comment]
> The series ACL update to Opencast only happens when there is a change to the ACL set! So, to make sure that happens and works correctly, you would need to change ACLs in ILIAS (I think it could be achieved by changing PermissionTemplate!) and then update metadata.

That is certainly not the current behavior @dagraf described above.. We don't use Permission templates. Also, it's something entirely different to change a global setting and updating a series ACL with the current course admins. Or am I missing important information here?

**Comment by dagraf** [comment]
After discussing with @ferishili what this PR changes the behavior I described above will not be edited. Therefore, I would suggest we test this PR. Myself, I will not be able to test it before the end of July. @tscheere: You reported this issue. Could you test this PR in the next days?

**Comment by tscheere** [comment]
@dagraf we are probably able to patch and test this some time next week.

**Comment by tscheere** [comment]
@dagraf we tested this and it works.

**Environment:**
ILIAS version: [v8.13 2024-06-25]
PHP version: [PHP 7.4.33]
Plugin version: [8.0.7]
Opencast version [15.5.0]

**Comment by dagraf** [comment]
Thx for testing, @tscheere.

Therefore and @ferishili: Can you please prepare this PR for merging and when done contact @chfsx? Thx!

**Pull request merged**
