### PR TITLE
[FIX] 131: Storing Metadata

### PR DESCRIPTION
**Pull request by chfsx**
This fixes several issues with metadata of series:
- #131 
- #152 
- #140 

could please someone test this?

One question concerning "Permission Templates": If there is no "Permission Templates" in "Video Portal" > "Permission Templates" configured, the error `addToAcls on null` can occur. Are permission templates mandatory? if so, we should introduce at least one default template with an db update step or implement a fallback. I just check the availability of e template now before call addToAcls.

### CODE REVIEW

**Comment by dagraf** [comment]
Thx for the fix. We will run some tests and will communicate our results here. But since we can not reproduce #151 (@fsesterh) and #152 (@ralede) (because we are not on OC-13 yet) our tests are only of limited use. Therefore I will asks the persons who reported these issues to run tests, too.

**Comment by dagraf** [comment]
According to @chfsx issue #131 should also be fixed by this fix.

Testings will show. :)

**Comment by chfsx** [comment]
now i see my mistake, i mentioned 151 instead of 131 above :)

**Comment by fsesterh** [comment]
I tried to check the branch from @chfsx but after I checked it out the plugin was deactivated (was on opencast:main before). Updating the plugin crashes. Log attached. Switching back to opencast:main does not fix this. Don't know what to do and how to test your PR :/
[omfa3_5154.log](https://github.com/opencast-ilias/OpenCast/files/11287225/omfa3_5154.log)

**Comment by chfsx** [comment]
@fsesterh this is very strange... the branch srsolutionsag:fix/131 is on top of main (last commit before my changes is: https://github.com/srsolutionsag/OpenCast/commit/837e15be2b0acbfd932bc787eb8b1a2a9d45a98d ). which version (from main) did you have before?

your error mentions the https://github.com/opencast-ilias/OpenCast/blob/main/doc/migration.md readme we made before releasing 4.0.0

**Comment by fsesterh** [comment]
How can I check what commit I was on before I pulled? 

I did not backup the folder before I pulled/switched to your repo/branch.
I reimported my database backup from the day before and switched to the opencast:main branch which is V5.1.0. According to the plugin info I am on database update step 37, which should mean that I went through the migration process before (<=36 to 37 or above). Plugin version 5.1.0 needs an update from 37 to 39, but your branch or opencast:main crashes with the same error.

So this must not be your PR. Anyway, database version 37 means I went through the migration correct? I remember going through it.

**Comment by ralede** [comment]
By creating a permission template, it works with Opencast 13 (educast.nrw). Thank you!
Screenshot_Berechtigungsvorlage

**Comment by chfsx** [comment]
is something still open here, or is this PR ready to be merged?

**Comment by dagraf** [comment]
All is fine in this PR. We (@okaufman) will do a riview and merge it if everything looks good.

**Pull request merged**
