### PR TITLE
Fix/7/248

### PR DESCRIPTION
**Pull request by chfsx**
This fixes issue #248 (configuration of chunk size) and the chunked upload in ILIAS 7 in general.

### CODE REVIEW

**Comment by reiferschris** [comment]
Hi @chfsx 
I tested this PR but it doesn't work for me. 
The upload animation is broken (see video) and after the animation/upload is finished and I click on save it says: `There is an error in this part' (fileupload) `No files selected'

Apparently this happens for files that are larger than the configured chunk size (tested with 20MB and 100MB)

https://github.com/opencast-ilias/OpenCast/assets/34450887/6dd98d17-beb2-4a6a-9a6b-a2d5d2edb255
The effect seen in this video is more pronounced when uploading larger files. 


The configuration values in the settings are fine now and it doesn't complain about the `post_max_size` anymore and accepts files up to the configured limit in the plugin.

**Comment by chfsx** [comment]
@reiferschris thanks for the feedback. just to be sure: the browser cache is completely deleted? because otherwise there could be problems due to the adjustments in the JS. I deliberately tested with large (larger than chunk-size) as well as small files, both worked. the behavior of the progress-basr is really very strange... but i will also test again and try to reproduce the behavior from the video.

**Comment by reiferschris** [comment]
I retested with deleted cache in Firefox, with Safari and in Chromium. None of them work, all of them show the behavior in the video but not as pronouncend ( I suspect that might be depending on the chunksize?) and after the upload is finished an I can click on save it complains "No files selected" if the file size is larger than the configured chunk size.
Any hints what I can do to further debug this?

```
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:01 +0000] "GET /ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 12032 "https://lms.dev/ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /src/UI/templates/js/ViewControl/sortation.js?version=7_25 HTTP/1.1" 200 767 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /src/UI/templates/js/ViewControl/pagination.js?version=7_25 HTTP/1.1" 200 813 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /src/UI/templates/js/Input/Field/input.js?version=7_25 HTTP/1.1" 200 751 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /src/UI/templates/js/Input/Container/dist/filter.js?version=7_25 HTTP/1.1" 200 3618 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /src/UI/templates/js/Popover/popover.js?version=7_25 HTTP/1.1" 200 1574 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /src/UI/templates/js/MainControls/footer.js?version=7_25 HTTP/1.1" 200 531 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /src/UI/templates/js/Dropdown/dropdown.js?version=7_25 HTTP/1.1" 200 623 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /libs/bower/bower_components/webui-popover/dist/jquery.webui-popover.js?version=7_25 HTTP/1.1" 200 8978 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /src/UI/templates/js/Input/Field/groups.js?version=7_25 HTTP/1.1" 200 810 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/templates/default/events.js?version=7_25 HTTP/1.1" 200 967 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /Services/Table/js/ServiceTable.js?version=7_25 HTTP/1.1" 200 1109 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /favicon.ico HTTP/1.1" 200 1706 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | [24-04-03 09:18:02] [unknown] execute *************************************************
ilias_7  | [24-04-03 09:18:02] [unknown] https://admin.dev./api/events?filter=series:d2556071-030a-4c9a-82fe-a6d6987c5888&withmetadata=false&withacl=true&withpublications=true&withscheduling=true&sign=false&offset=0&limit=1000
ilias_7  | [24-04-03 09:18:02] [unknown] GET
ilias_7  | [24-04-03 09:18:02] [unknown] CONNECT_TIME: 2.54 ms
ilias_7  | [24-04-03 09:18:02] [unknown] NAMELOOKUP_TIME: 1.95 ms
ilias_7  | [24-04-03 09:18:02] [unknown] REDIRECT_TIME: 0 ms
ilias_7  | [24-04-03 09:18:02] [unknown] STARTTRANSFER_TIME: 238.21 ms
ilias_7  | [24-04-03 09:18:02] [unknown] PRETRANSFER_TIME: 15.52 ms
ilias_7  | [24-04-03 09:18:02] [unknown] TOTAL_TIME: 238.62 ms
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&async=true HTTP/1.1" 200 4441 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:02 +0000] "GET /Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/templates/images/no_preview.png HTTP/1.1" 200 14769 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:03 +0000] "GET /ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 10487 "https://lms.dev/ilias.php?ref_id=92&cmd=index&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:04 +0000] "GET /src/UI/templates/js/Input/Field/textarea.js?version=7_25 HTTP/1.1" 200 903 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:04 +0000] "GET /src/UI/templates/js/Input/Field/duration.js?version=7_25 HTTP/1.1" 200 769 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:04 +0000] "GET /src/UI/templates/js/Input/Field/tagInput.js?version=7_25 HTTP/1.1" 200 1544 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:04 +0000] "GET /libs/bower/bower_components/dropzone/dist/min/dropzone.min.js?version=7_25 HTTP/1.1" 200 13368 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:04 +0000] "GET /node_modules/@yaireo/tagify/dist/tagify.min.js?version=7_25 HTTP/1.1" 200 16118 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:04 +0000] "GET /Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/templates/default/chunked_file.js?version=7_25 HTTP/1.1" 200 2320 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:04 +0000] "GET /src/UI/templates/js/Input/Field/file.js?version=7_25 HTTP/1.1" 200 2085 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 127.0.0.1 - - [03/Apr/2024:07:18:11 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.54 (Debian) PHP/7.4.33 (internal dummy connection)"
ilias_7  | 127.0.0.1 - - [03/Apr/2024:07:18:12 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.54 (Debian) PHP/7.4.33 (internal dummy connection)"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:10 +0000] "POST /ilias.php?ref_id=92&cmd=upload&cmdClass=xoctfileuploadhandlergui&cmdNode=p4:ow:178:17c&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 560 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:20 +0000] "POST /ilias.php?ref_id=92&cmd=upload&cmdClass=xoctfileuploadhandlergui&cmdNode=p4:ow:178:17c&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 559 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:30 +0000] "POST /ilias.php?ref_id=92&cmd=upload&cmdClass=xoctfileuploadhandlergui&cmdNode=p4:ow:178:17c&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 559 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:41 +0000] "POST /ilias.php?ref_id=92&cmd=upload&cmdClass=xoctfileuploadhandlergui&cmdNode=p4:ow:178:17c&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 559 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:18:51 +0000] "POST /ilias.php?ref_id=92&cmd=upload&cmdClass=xoctfileuploadhandlergui&cmdNode=p4:ow:178:17c&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 559 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:19:05 +0000] "GET /ilias.php?baseClass=ilObjChatroomGUI&cmd=getOSDNotifications&cmdMode=asynch&max_age=1712128754 HTTP/1.1" 200 457 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:19:01 +0000] "POST /ilias.php?ref_id=92&cmd=upload&cmdClass=xoctfileuploadhandlergui&cmdNode=p4:ow:178:17c&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 559 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:19:11 +0000] "POST /ilias.php?ref_id=92&cmd=upload&cmdClass=xoctfileuploadhandlergui&cmdNode=p4:ow:178:17c&baseClass=ilObjPluginDispatchGUI HTTP/1.1" 200 559 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 127.0.0.1 - - [03/Apr/2024:07:19:28 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.54 (Debian) PHP/7.4.33 (internal dummy connection)"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:05 +0000] "GET /ilias.php?baseClass=ilObjChatroomGUI&cmd=getOSDNotifications&cmdMode=asynch&max_age=70 HTTP/1.1" 200 457 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:10 +0000] "POST /ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca HTTP/1.1" 200 10552 "https://lms.dev/ilias.php?ref_id=92&cmd=add&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:11 +0000] "GET /src/UI/templates/js/Input/Field/input.js?version=7_25 HTTP/1.1" 200 752 "https://lms.dev/ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:11 +0000] "GET /src/UI/templates/js/Input/Field/tagInput.js?version=7_25 HTTP/1.1" 200 1545 "https://lms.dev/ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:11 +0000] "GET /src/UI/templates/js/Input/Field/textarea.js?version=7_25 HTTP/1.1" 200 904 "https://lms.dev/ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:11 +0000] "GET /src/UI/templates/js/Input/Field/duration.js?version=7_25 HTTP/1.1" 200 770 "https://lms.dev/ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:11 +0000] "GET /node_modules/@yaireo/tagify/dist/tagify.min.js?version=7_25 HTTP/1.1" 200 16118 "https://lms.dev/ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:11 +0000] "GET /libs/bower/bower_components/dropzone/dist/min/dropzone.min.js?version=7_25 HTTP/1.1" 200 13369 "https://lms.dev/ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 134.x.x.x - - [03/Apr/2024:07:20:11 +0000] "GET /favicon.ico HTTP/1.1" 200 1706 "https://lms.dev/ilias.php?ref_id=92&cmd=post&cmdClass=xocteventgui&cmdNode=p4:ow:178&baseClass=ilObjPluginDispatchGUI&fallbackCmd=create&rtoken=e33ee7a983cd372785dbea102b0a13ca" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"
ilias_7  | 127.0.0.1 - - [03/Apr/2024:07:20:18 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.54 (Debian) PHP/7.4.33 (internal dummy connection)"
```

**Comment by dagraf** [comment]
I tested this PR, too. It works for us. I configured 20MB as chunk size for the upload and was able to upload small (5MB) and larger videos (100MB). 

Since Christoph ran into a problem, @DZenker: You reported this issue. Can you also test this bugfix and report your results here? Thx!

**Comment by WKarlHGU** [comment]
I can also confirm that the PR solves the problem.

**Comment by dagraf** [comment]
Thx for testing. Since two institutions successfully tested this PR a suggest that we merge this PR. 
Therefore and @Amstutz: Can you please review this PR and comment or merge it, depending on your results? Thank you!

**Comment by rfcmaXi** [comment]
If relevant: I have also tested this pull for us, chunk can now be set and upload works.

**Comment by chfsx** [comment]
@Amstutz thank you for taking care of the merge of this PR. currently the fix seems to work for most people, but the feedback from @reiferschris is still open. i have not been able to observe or reproduce the behavior so far, so at the moment i have no idea where the problem comes from.

**Comment by chfsx** [comment]
addendum: we should definitely publish a new version each time such fixes are merged.

**Comment by Amstutz** [comment]
I had a walkthrough with @chfsx on this PR. Thx a lot @chfsx !

The baseline is that changes of the new File Upload from ILIAS 9 had to be pushed down to 8 and 7. This was not without issues.  We used to have JS from 8 in the version of 7, causing issue. Lots of the code in this PR is reverting those changes, however also adding a few new lines making this work again.

I consider this a big improvement over the status quo, and I am willing to merge this in this stage. However, @reiferschris if you can still reproduce your issues, please create a new issue, with steps to reproduce it (including browser etc.). So we can track this separately and break this down in multiple iterations.

**Pull request merged**
