### PR TITLE
Implemented License as Metadatum

### PR DESCRIPTION
**Pull request by chfsx**
Hi @okaufman 

To test this version, you need to come from version 5.0.1 and DB Version 38. I had to switch off DB-Cache in my settings to get it to work.

With this changes you can configure Licenses as a Metadatum for Series:

image

one must configure the possible values to Match the values of opencast itself (e.g. 

```
ALLRIGHTS|||Alle Rechte vorbehalten
CC-BY|||CC BY
```

### CODE REVIEW

**Comment by okaufman** [comment]
Thank you, I think this works good enough. One Problem I encountered is that I always ran into a problem when accessing the "settings" page of an already existing series: 
Argument 'value': Display value does not match input type. in /var/www/ilias-next/src/UI/Implementation/Component/ComponentHelper.php:67#0 /var/www/ilias-next/src/UI/Implementation/Component/Input/Field/Input.php(230): ILIAS\UI\Implementation\Component\Input\Field\Input->checkArg('value', false, 'Display value d...'

I could solve this by adding another license in the metadata-config that was just "-|||-" 
 "-" was saved as a license in old series when the users did not choose a specific license. 
This means that in the dropdown "-" will appear twice
Bildschirmfoto 2023-01-10 um 10 58 09

**Comment by okaufman** [comment]
Maybe you could expect the "-" as a value and handle that somehow.
This is the full path of the error:
ilias3_unibe_root.ERROR: ilErrorHandling::{closure}:50 0 Argument 'value': Display value does not match input type. in /var/www/ilias-next/src/UI/Implementation/Component/ComponentHelper.php:67#0 /var/www/ilias-next/src/UI/Implementation/Component/Input/Field/Input.php(230): ILIAS\UI\Implementation\Component\Input\Field\Input->checkArg('value', false, 'Display value d...')
#1 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/UI/Metadata/MDFormItemBuilder.php(217): ILIAS\UI\Implementation\Component\Input\Field\Input->withValue('-')
#2 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/UI/Metadata/MDFormItemBuilder.php(123): srag\Plugins\Opencast\UI\Metadata\MDFormItemBuilder->buildFormElementForMDField(Object(srag\Plugins\Opencast\Model\Metadata\Config\Series\MDFieldConfigSeriesAR), '-')
#3 [internal function]: srag\Plugins\Opencast\UI\Metadata\MDFormItemBuilder->srag\Plugins\Opencast\UI\Metadata\{closure}(Object(srag\Plugins\Opencast\Model\Metadata\Config\Series\MDFieldConfigSeriesAR), 5)
#4 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/UI/Metadata/MDFormItemBuilder.php(125): array_walk(Array, Object(Closure))
#5 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/UI/SeriesFormBuilder.php(100): srag\Plugins\Opencast\UI\Metadata\MDFormItemBuilder->update_section(Object(srag\Plugins\Opencast\Model\Metadata\Metadata), true)
#6 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Series/class.xoctSeriesGUI.php(152): srag\Plugins\Opencast\UI\SeriesFormBuilder->update('ilias.php?ref_i...', Object(srag\Plugins\Opencast\Model\Object\ObjectSettings), Object(srag\Plugins\Opencast\Model\Series\Series), true)
#7 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php(46): xoctSeriesGUI->editGeneral()
#8 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php(35): xoctGUI->performCommand('editGeneral')
#9 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Series/class.xoctSeriesGUI.php(94): xoctGUI->executeCommand()
#10 /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php(217): xoctSeriesGUI->executeCommand()
#11 /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php(156): ilCtrl->forwardCommand(Object(xoctSeriesGUI))
#12 /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php(217): ilObjOpenCastGUI->executeCommand()
#13 /var/www/ilias-next/Services/Repository/classes/class.ilObjPluginDispatchGUI.php(45): ilCtrl->forwardCommand(Object(ilObjOpenCastGUI))
#14 /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php(217): ilObjPluginDispatchGUI->executeCommand()
#15 /var/www/ilias-next/Services/UICore/classes/class.ilCtrl.php(178): ilCtrl->forwardCommand(Object(ilObjPluginDispatchGUI))
#16 /var/www/ilias-next/ilias.php(23): ilCtrl->callBaseClass()
#17 {main}

**Comment by chfsx** [comment]
I updated the branch to prevent this issue, could you test it again please?

**Comment by chfsx** [comment]
Unfortunately, this is not possible. The "-" generally comes from the select input and cannot be renamed and means "no value". Moreover, the implementation for the licences here is generic, like all other metadata fields. This means that the licence field is not a specific "licence field" but a general one of the type "text selection", of which there may be others.

**Comment by okaufman** [comment]
Thank you very much for this PR

**Pull request merged**
