### PR TITLE
[Release 8] fix broken ACL xml and startDate xml metadata when using ingest upload

### LINKED ISSUE #349: Wrong event ACL if event is created with manually uploaded subtitle file
**Describe the bug**
Opencast events created in ILIAS with manually uploaded subtitles can't be watched in Opencast and won't be displayed in Tobira, even if the user is authorised for the corresponding series.

When I compare the Opencast event/episode ACL of ILIAS-created events with and without subtitles, I see that the XMLs are completely different. In the XML for the event with subtitles, I can see a comment indicating that it was generated by the "ILIAS XmlWriter". :

OC event without subtitles:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Policy PolicyId="b6827349-a1c4-44d3-899b-fbe925d080f0" Version="2.0"
    RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:permit-overrides"
    xmlns="urn:oasis:names:tc:xacml:2.0:policy:schema:os">
    <Target>
        <Resources>
            <Resource>
                <ResourceMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                    <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                        b6827349-a1c4-44d3-899b-fbe925d080f0</AttributeValue>
                    <ResourceAttributeDesignator
                        AttributeId="urn:oasis:names:tc:xacml:1.0:resource:resource-id"
                        DataType="http://www.w3.org/2001/XMLSchema#string" />
                </ResourceMatch>
            </Resource>
        </Resources>
    </Target>
    <Rule RuleId="ROLE_AAI_USER_xyz_write_Permit"
        Effect="Permit">
        <Target>
            <Actions>
                <Action>
                    <ActionMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                        <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">write</AttributeValue>
                        <ActionAttributeDesignator
                            AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id"
                            DataType="http://www.w3.org/2001/XMLSchema#string" />
                    </ActionMatch>
                </Action>
            </Actions>
        </Target>
        <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                    ROLE_AAI_USER_xyz</AttributeValue>
                <SubjectAttributeDesignator AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
                    DataType="http://www.w3.org/2001/XMLSchema#string" />
            </Apply>
        </Condition>
    </Rule>
    <Rule RuleId="ROLE_AAI_USER_xyz_read_Permit"
        Effect="Permit">
        <Target>
            <Actions>
                <Action>
                    <ActionMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                        <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">read</AttributeValue>
                        <ActionAttributeDesignator
                            AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id"
                            DataType="http://www.w3.org/2001/XMLSchema#string" />
                    </ActionMatch>
                </Action>
            </Actions>
        </Target>
        <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                    ROLE_AAI_USER_xyz</AttributeValue>
                <SubjectAttributeDesignator AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
                    DataType="http://www.w3.org/2001/XMLSchema#string" />
            </Apply>
        </Condition>
    </Rule>
    <Rule RuleId="DenyRule" Effect="Deny" />
</Policy>
```

OC event with subtitles:
```
<?xml version="1.0" encoding="utf-8"?><!--Generated by ILIAS XmlWriter-->
<Policy PolicyId="mediapackage-1"
    RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:permit-overrides"
    Version="2.0" xmlns="urn:oasis:names:tc:xacml:2.0:policy:schema:os">
    <Rule RuleId="user_write_permit" Effect="Permit">
        <Target>
            <Actions>
                <Action>
                    <ActionMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                        <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">write</AttributeValue>
                        <ActionAttributeDesignator
                            AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id"
                            DataType="http://www.w3.org/2001/XMLSchema#string" />
                    </ActionMatch>
                </Action>
            </Actions>
        </Target>
        <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                    ROLE_AAI_USER_xyz</AttributeValue>
                <SubjectAttributeDesignator AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
                    DataType="http://www.w3.org/2001/XMLSchema#string" />
            </Apply>
        </Condition>
    </Rule>
    <Rule RuleId="user_read_permit" Effect="Permit">
        <Target>
            <Actions>
                <Action>
                    <ActionMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                        <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">read</AttributeValue>
                        <ActionAttributeDesignator
                            AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id"
                            DataType="http://www.w3.org/2001/XMLSchema#string" />
                    </ActionMatch>
                </Action>
            </Actions>
        </Target>
        <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                    ROLE_AAI_USER_xyz</AttributeValue>
                <SubjectAttributeDesignator AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
                    DataType="http://www.w3.org/2001/XMLSchema#string" />
            </Apply>
        </Condition>
    </Rule>
</Policy>
```

**To Reproduce**
1. Go to an Opencast series in ILIAS
2. Click on 'Upload Event', add a new event with a subtitle file and publish it directly
3. Go to Opencast, login as non-admin user with access to the series
4. Try to play the newly created video and see the error in the Paella player

**Expected behavior**
Event-ACL for events with subtitles should be set correctly as it is done for events without subtitles. 

**Environment (please complete the following information):**
 - ILIAS version: v8.14 2024-08-13
 - Plugin version: 8.1.4
 - Opencast version: 15

**Additional context**
The same problem applies if you upload a thumbnail instead of subtitles (feature introduced by https://github.com/opencast-ilias/OpenCast/pull/305).

### LINKED ISSUE #350: Incorrect start date when creating event with manually uploaded subtitle file
**Describe the bug**
Opencast events created in ILIAS with manually uploaded subtitles have an incorrect start date/time. Instead of the current date/time, the start date/time of the new event is the current time +2h. For events without subtitles, the start date/time is set correctly.

**To Reproduce**
1. Go to an Opencast series in ILIAS
2. Click on 'Upload Event', add a new event with a subtitle file and publish it directly
3. The start date of the new event is the current time +2h

**Expected behavior**
The start date/time of uploaded events with subtitles should be the creation date/time.

**Environment (please complete the following information):**
 - ILIAS version: v8.14 2024-08-13
 - Plugin version: 8.1.4
 - Opencast version: 15

**Additional context**
The same problem applies if you upload a thumbnail instead of subtitles (feature introduced by https://github.com/opencast-ilias/OpenCast/pull/305).

### PR DESCRIPTION
**Pull request by ferishili**
This PR
fixes #350
fixes #349

## Problem:
When using Ingest to upload videos:
- startDate metadata is shown +2h
- ACLs are broken and faulty

## Solution
- startDate => has to have GMT as its timezone
- ACLs XML generator now has all the missing tags and incompelete tag id and resources.

### CODE REVIEW

**Comment by ferishili** [comment]
Hi @snoesberger,
Please try this PR and let me know your feedback.

**Attention:** the PR has been prepared on top of v8.2.2, therefore you might need to perform an update in order to test!

**Comment by okaufman** [comment]
Hello Farbod
I have a question. Is this PR also going to work for people in a different timezone? When they are not using GMT

**Comment by ferishili** [comment]
Hi Olivia,

> I have a question. Is this PR also going to work for people in a different timezone? When they are not using GMT

According to what is actually used in other places throughout the code, and specially the normal upload, it appears that GMT timezone would work fine, at least so far among the community. Take a look at these places:

https://github.com/opencast-ilias/OpenCast/blob/b6a5bbe6fef237ea3ab2964a3e1bcaea6aa00dff/src/Model/Metadata/Helper/MDParser.php#L221

https://github.com/opencast-ilias/OpenCast/blob/b6a5bbe6fef237ea3ab2964a3e1bcaea6aa00dff/src/Model/Scheduling/Scheduling.php#L49

https://github.com/opencast-ilias/OpenCast/blob/b6a5bbe6fef237ea3ab2964a3e1bcaea6aa00dff/src/Model/Scheduling/SchedulingParser.php#L40

Based on what I could understand, it works somehow as “neutral” when using "GMT" timezone, and takes the actual current local datetime(!?)

**Comment by snoesberger** [comment]
> Hi @snoesberger, Please try this PR and let me know your feedback.
> 
> **Attention:** the PR has been prepared on top of v8.2.2, therefore you might need to perform an update in order to test!

Thanks! The date is now set correctly (just tested it for CEST), but the event/episode ACL are still not correctly set. I can't see the videos uploaded with subtitles in Tobira.

The ACL set by ILIAS looks now like this:
```
<?xml version="1.0" encoding="utf-8"?><!--Opencast ILIAS Plugin Access Policy Generator-->
<Policy PolicyId="350c13ba-be0f-441c-adf6-0156485359db"
    RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:permit-overrides"
    Version="2.0" xmlns="urn:oasis:names:tc:xacml:2.0:policy:schema:os">
    <Rule RuleId="ROLE_AAI_USER_xyz_write_permit"
        Effect="Permit">
        <Target>
            <Actions>
                <Action>
                    <ActionMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                        <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">write</AttributeValue>
                        <ActionAttributeDesignator
                            AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id"
                            DataType="http://www.w3.org/2001/XMLSchema#string" />
                    </ActionMatch>
                </Action>
            </Actions>
        </Target>
        <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                    ROLE_AAI_USER_xyz</AttributeValue>
                <SubjectAttributeDesignator AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
                    DataType="http://www.w3.org/2001/XMLSchema#string" />
            </Apply>
        </Condition>
    </Rule>
    <Rule RuleId="ROLE_AAI_USER_xyz_read_permit"
        Effect="Permit">
        <Target>
            <Actions>
                <Action>
                    <ActionMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                        <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">read</AttributeValue>
                        <ActionAttributeDesignator
                            AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id"
                            DataType="http://www.w3.org/2001/XMLSchema#string" />
                    </ActionMatch>
                </Action>
            </Actions>
        </Target>
        <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                    ROLE_AAI_USER_xyz</AttributeValue>
                <SubjectAttributeDesignator AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
                    DataType="http://www.w3.org/2001/XMLSchema#string" />
            </Apply>
        </Condition>
    </Rule>
    <Rule RuleId="DenyRule" Effect="Deny" />
</Policy>
```

This is how the ACL looks like if I create an event directly in Opencast which is correctly displayed in Tobira:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Policy PolicyId="34990d39-37ec-4705-a637-9d53b72f4e63" Version="2.0"
    RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:permit-overrides"
    xmlns="urn:oasis:names:tc:xacml:2.0:policy:schema:os">
    <Target>
        <Resources>
            <Resource>
                <ResourceMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                    <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                        34990d39-37ec-4705-a637-9d53b72f4e63</AttributeValue>
                    <ResourceAttributeDesignator
                        AttributeId="urn:oasis:names:tc:xacml:1.0:resource:resource-id"
                        DataType="http://www.w3.org/2001/XMLSchema#string" />
                </ResourceMatch>
            </Resource>
        </Resources>
    </Target>
    <Rule RuleId="ROLE_AAI_USER_xyz_read_Permit"
        Effect="Permit">
        <Target>
            <Actions>
                <Action>
                    <ActionMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                        <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">read</AttributeValue>
                        <ActionAttributeDesignator
                            AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id"
                            DataType="http://www.w3.org/2001/XMLSchema#string" />
                    </ActionMatch>
                </Action>
            </Actions>
        </Target>
        <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                    ROLE_AAI_USER_xyz</AttributeValue>
                <SubjectAttributeDesignator AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
                    DataType="http://www.w3.org/2001/XMLSchema#string" />
            </Apply>
        </Condition>
    </Rule>
    <Rule RuleId="ROLE_AAI_USER_xyz_write_Permit"
        Effect="Permit">
        <Target>
            <Actions>
                <Action>
                    <ActionMatch MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                        <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">write</AttributeValue>
                        <ActionAttributeDesignator
                            AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id"
                            DataType="http://www.w3.org/2001/XMLSchema#string" />
                    </ActionMatch>
                </Action>
            </Actions>
        </Target>
        <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">
                    ROLE_AAI_USER_xyz</AttributeValue>
                <SubjectAttributeDesignator AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
                    DataType="http://www.w3.org/2001/XMLSchema#string" />
            </Apply>
        </Condition>
    </Rule>
    <Rule RuleId="DenyRule" Effect="Deny" />
</Policy>
```

In the ILIAS-generated ACL the first `Target` section is missing.

**Comment by ferishili** [comment]
Hi @snoesberger,
thanks for your feedback, I have added the resource id traget tag.
This resource id target tag was not needed before (and there is very little documentation on this part), as it is also implemented and working in Moodle plugin without this tag. I would assume, that is either a very new addition like OC 15+ or your OC setup configuration specific. In this case, I would strongly suggest that this PR gets tested also with other OC setups (e.g. by Köln)
What do you think?

**Comment by snoesberger** [comment]
> Hi @snoesberger, thanks for your feedback, I have added the resource id traget tag. This resource id target tag was not needed before (and there is very little documentation on this part), as it is also implemented and working in Moodle plugin without this tag. I would assume, that is either a very new addition like OC 15+ or your OC setup configuration specific. In this case, I would strongly suggest that this PR gets tested also with other OC setups (e.g. by Köln) What do you think?

Thanks for the update @ferishili. In our case the problem only affects Tobira, where videos uploaded to ILIAS with subtitles/thumbnails are not displayed at all. In Opencast and ILIAS these videos are shown to the authorised users and can be watched.
And yes, I can imagine that the OC version or the configured merge mode for event/series rights in Opencast can have an impact on the behaviour. So it would be great if another institution could also test this PR (if possible someone who also has Tobira installed).

**Comment by snoesberger** [comment]
@ferishili I have tested your changes and the videos are still not visible in Tobira. I found one more difference in the ILIAS generated ACL, in the first `Target` section (which you added with your last change) in the xml the tag `ActionAttributeDesignator` is used instead of the tag `ResourceAttributeDesignator` which is used in the OC generated ACL. Hopefully this is the last missing piece.

**Comment by ferishili** [comment]
You are 100% right, I missed that, please try it again

**Comment by snoesberger** [comment]
Sorry @ferishili but it still doesn't work in Tobira... The xml content looks fine to me now, I can't see any differences. So I checked the ACL file itself. The path to the ACL file generated by ILIAS looks like this:
https://my-opencast.org/assets/assets/145a09cf-427e-4132-9303-0a909de23f55/67577e5a-f930-4930-b114-69a3cf2d4240/6/tmp66d1a55e1252a
whereas the path to a correctly interpreted ACL file looks like this:
https://my-opencast.org/assets/assets/c7cd3531-0f32-4960-abbe-f6af29658c60/security-policy-episode/9/xacml.xml

As you can see, the file generated by ILIAS has no xml ending and looks more like a temporary file. Maybe this could be a problem for Tobira? Do you have any idea why the ACL file looks like that and how it could be changed?

**Comment by ferishili** [comment]
Sorry to hear that,
I have an idea where that could come from, I will prepare a fix asap.

**Comment by ferishili** [comment]
@snoesberger; please try it again

**Comment by snoesberger** [comment]
Thanks @ferishili! Adding the xml-extension did the trick, now the videos are also displayed correctly in Tobira.

**Comment by ferishili** [comment]
Happy to hear that, thank you as well 👍

**Comment by dagraf** [comment]
Thx for fixing and testing. @chfsx: Can you please review this PR and comment it or merge it if everything is fine? Thx!

**Comment by dagraf** [comment]
> Thx for fixing and testing. @chfsx: Can you please review this PR and comment it or merge it if everything is fine? Thx!

@chfsx Reminder. Thx!

**Comment by chfsx** [comment]
merged locally in new version

**Pull request closed without merging**
